import dotenv from "dotenv";
import { WinnerManagementProfile } from "../domain/types";

dotenv.config();


export const EARLY_ROOT_DIR = process.cwd();
export const IS_WORKER_PROCESS = !!process.env.WORKER_TASK_SIGNATURE;
export const WORKER_SLOT = Number(process.env.WORKER_SLOT || 0);
export const SILENCE_RPC_429_LOGS = process.env.SILENCE_RPC_429_LOGS !== "false";

export const CONFIG = {
    TRADE_AMOUNT_SOL: 0.01,
    MIN_POOL_LIQUIDITY_USD: 10000,
    MIN_POOL_LIQUIDITY_SOL: 20,
    AUTO_SELL_DELAY_MS: Number(900000),
    HOLD_SUSPICIOUS_RELAY_SHORT_HOLD_ENABLED: true,
    HOLD_SUSPICIOUS_RELAY_SHORT_HOLD_MS: Number(15000),
    HOLD_REMOVE_LIQ_DETECT_ENABLED: true,
    HOLD_REMOVE_LIQ_CHECK_INTERVAL_MS: Number(1500),
    HOLD_REMOVE_LIQ_MIN_WSOL_TO_CREATOR: Number(0.5),
    HOLD_REMOVE_LIQ_MIN_SOL_TO_CREATOR: Number(0.5),
    HOLD_CREATOR_AMM_BURST_DETECT_ENABLED: true,
    HOLD_CREATOR_AMM_BURST_WINDOW_SEC: Number(8),
    HOLD_CREATOR_AMM_BURST_MIN_TXS: Number(3),
    HOLD_CREATOR_OUTBOUND_EXIT_ENABLED: true,
    HOLD_CREATOR_OUTBOUND_CHECK_INTERVAL_MS: Number(1500),
    HOLD_CREATOR_OUTBOUND_MIN_SOL: Number(10),
    HOLD_CREATOR_CLOSE_ACCOUNT_BURST_EXIT_ENABLED: true,
    HOLD_CREATOR_CLOSE_ACCOUNT_BURST_CHECK_INTERVAL_MS: Number(1000),
    HOLD_CREATOR_CLOSE_ACCOUNT_BURST_WINDOW_SEC: Number(20),
    HOLD_CREATOR_CLOSE_ACCOUNT_BURST_MIN_TXS: Number(3),
    HOLD_CREATOR_CLOSE_ACCOUNT_BURST_MIN_CLOSES: Number(12),
    HOLD_CREATOR_OUTBOUND_SPRAY_EXIT_ENABLED: true,
    HOLD_CREATOR_OUTBOUND_SPRAY_CHECK_INTERVAL_MS: Number(1500),
    HOLD_CREATOR_OUTBOUND_SPRAY_WINDOW_SEC: Number(30),
    HOLD_CREATOR_OUTBOUND_SPRAY_MIN_TRANSFERS: Number(20),
    HOLD_CREATOR_OUTBOUND_SPRAY_MIN_DESTINATIONS: Number(20),
    HOLD_CREATOR_OUTBOUND_SPRAY_MAX_MEDIAN_SOL: Number(0.05),
    HOLD_CREATOR_OUTBOUND_SPRAY_MAX_REL_STDDEV: Number(0.2),
    HOLD_CREATOR_OUTBOUND_SPRAY_MAX_AMOUNT_RATIO: Number(3),
    HOLD_CREATOR_INBOUND_SPRAY_EXIT_ENABLED: true,
    HOLD_CREATOR_INBOUND_SPRAY_CHECK_INTERVAL_MS: Number(1500),
    HOLD_CREATOR_INBOUND_SPRAY_WINDOW_SEC: Number(30),
    HOLD_CREATOR_INBOUND_SPRAY_MIN_TRANSFERS: Number(8),
    HOLD_CREATOR_INBOUND_SPRAY_MIN_SOURCES: Number(8),
    HOLD_CREATOR_INBOUND_SPRAY_MAX_REL_STDDEV: Number(0.12),
    HOLD_CREATOR_INBOUND_SPRAY_MAX_AMOUNT_RATIO: Number(1.35),
    HOLD_POOL_CHURN_DETECT_ENABLED: true,
    HOLD_POOL_CHURN_CHECK_INTERVAL_MS: Number(1500),
    HOLD_POOL_CHURN_SIG_LIMIT: Number(60),
    HOLD_POOL_CHURN_WINDOW_SHORT_MS: Number(10000),
    HOLD_POOL_CHURN_WINDOW_LONG_MS: Number(20000),
    HOLD_POOL_CHURN_WINDOW_CRITICAL_MS: Number(40000),
    HOLD_POOL_CHURN_TX_SHORT_MIN: Number(10),
    HOLD_POOL_CHURN_TX_LONG_MIN: Number(20),
    HOLD_POOL_CHURN_TX_CRITICAL_MIN: Number(30),
    HOLD_POOL_CHURN_SELL_DROP_PCT: Number(50),
    HOLD_POOL_CHURN_CRITICAL_SELL_DROP_PCT: Number(35),
    HOLD_SELL_QUOTE_COLLAPSE_EXIT_ENABLED: true,
    HOLD_SELL_QUOTE_COLLAPSE_CHECK_INTERVAL_MS: Number(300),
    HOLD_SELL_QUOTE_COLLAPSE_MIN_HOLD_MS: Number(3000),
    HOLD_SELL_QUOTE_COLLAPSE_DROP_PCT: Number(35),
    HOLD_SELL_QUOTE_COLLAPSE_MIN_SOL: Number(0.0025),
    HOLD_SINGLE_SWAP_SHOCK_EXIT_ENABLED: true,
    HOLD_SINGLE_SWAP_SHOCK_CHECK_INTERVAL_MS: Number(300),
    HOLD_SINGLE_SWAP_SHOCK_MIN_HOLD_MS: Number(3000),
    HOLD_SINGLE_SWAP_SHOCK_DROP_PCT: Number(35),
    HOLD_HARD_STOP_LOSS_EXIT_ENABLED: true,
    HOLD_HARD_STOP_LOSS_CHECK_INTERVAL_MS: Number(250),
    HOLD_HARD_STOP_LOSS_MIN_HOLD_MS: Number(3000),
    HOLD_HARD_STOP_LOSS_PCT: Number(15),
    HOLD_WINNER_MANAGEMENT_ENABLED: true,
    HOLD_WINNER_CHECK_INTERVAL_MS: Number(200),
    HOLD_WINNER_MIN_HOLD_MS: Number(4000),
    HOLD_WINNER_ARM_PNL_PCT: Number(8),
    HOLD_WINNER_TRAILING_DROP_PCT: Number(10),
    HOLD_WINNER_TRAILING_DROP_PCT_CP0: Number(10),
    HOLD_WINNER_HARD_TAKE_PROFIT_PCT: Number(50),
    HOLD_WINNER_HARD_TAKE_PROFIT_PCT_CP1: Number(50),
    HOLD_WINNER_MIN_PEAK_SOL: Number(0.0104),
    HOLD_WINNER_PROFIT_FLOOR_PCT: Number(3),
    HOLD_PROBATION_CASHOUT_DELTA_MIN_SOL: Number(5),
    HOLD_PROBATION_INTERVAL_MULTIPLIER: Number(0.4),
    PRE_BUY_REVALIDATION_ENABLED: true,
    PRE_BUY_FINAL_CREATOR_RISK_RECHECK_ENABLED: true,
    PRE_BUY_FINAL_REMOVE_LIQ_CHECK_ENABLED: true,
    PRE_BUY_REVALIDATION_MAX_LIQ_DROP_PCT: Number(35),
    PRE_BUY_REVALIDATION_MAX_QUOTE_VS_SPOT_RATIO: Number(25),
    PRE_BUY_WAIT_MS: Number(1500),
    PRE_BUY_SIGNAL_MIN_TRADES: Number(10),
    PRE_BUY_SIGNAL_MIN_QUOTE_IMPROVEMENT_PCT: Number(0),
    PRE_BUY_STRICT_SIGNAL_MIN_QUOTE_IMPROVEMENT_PCT: Number(0.25),
    PRE_BUY_MAX_LIQ_DROP_PCT: Number(10),
    PRE_BUY_CONFIRM_SNAPSHOTS: Number(3),
    PRE_BUY_CONFIRM_INTERVAL_MS: Number(350),
    PRE_BUY_NO_WSOL_RECHECK_ENABLED: true,
    PRE_BUY_NO_WSOL_RECHECK_MAX_ATTEMPTS: Number(10),
    PRE_BUY_NO_WSOL_RECHECK_INTERVAL_MS: Number(350),
    PRE_BUY_NO_WSOL_RECHECK_BACKOFF_MULTIPLIER: Number(1.35),
    PRE_BUY_NO_WSOL_RECHECK_MAX_INTERVAL_MS: Number(1200),
    FORCE_ENTRY_ON_NO_WSOL_SIDE: false,
    PRE_BUY_ULTRA_SHORT_RUG_GUARD_ENABLED: true,
    PRE_BUY_ULTRA_SHORT_RUG_GUARD_WINDOW_MS: Number(2500),
    PRE_BUY_ULTRA_SHORT_RUG_GUARD_INTERVAL_MS: Number(500),
    PRE_BUY_ULTRA_SHORT_RUG_GUARD_MAX_LIQ_DROP_PCT: Number(35),
    PRE_BUY_ULTRA_SHORT_RUG_GUARD_MAX_QUOTE_DROP_PCT: Number(35),
    PRE_BUY_TOP10_CHECK_ENABLED: true,
    PRE_BUY_TOP10_MAX_PCT: Number(90),
    PRE_BUY_TOP10_EXCLUDE_POOL: true,
    PRE_BUY_TOP1_EXTERNAL_HOLDER_CHECK_ENABLED: true,
    PRE_BUY_TOP1_EXTERNAL_HOLDER_MAX_PCT: Number(20),
    PRE_BUY_TOP10_FAIL_OPEN: false,
    PRE_BUY_TOP10_MAX_ATTEMPTS: Number(4),
    PRE_BUY_TOP10_RETRY_BASE_MS: Number(400),
    CREATOR_RISK_CHECK_ENABLED: true,
    CREATOR_RISK_SIG_LIMIT: Number(80),
    CREATOR_RISK_PARSED_TX_LIMIT: Number(50),
    CREATOR_RISK_CACHE_TTL_MS: Number(15 * 60 * 1000),
    CREATOR_RISK_MAX_UNIQUE_COUNTERPARTIES: Number(3),
    CREATOR_RISK_WHITELISTED_CC_VALUES: (process.env.CREATOR_RISK_WHITELISTED_CC_VALUES || "0,1,2,4,47")
        .split(",")
        .map((v) => Number(v.trim()))
        .filter((v) => Number.isFinite(v) && v >= 0),
    CREATOR_RISK_COMPRESSED_MAX_COUNTERPARTIES: Number(60),
    CREATOR_RISK_COMPRESSED_WINDOW_SEC: Number(90),
    CREATOR_RISK_BURNER_MIN_OUT_SOL: Number(100),
    CREATOR_RISK_FUNDER_CLUSTER_ENABLED: true,
    CREATOR_RISK_FUNDER_CLUSTER_MIN_CREATORS: Number(2),
    CREATOR_RISK_FUNDER_CLUSTER_WINDOW_SEC: Number(900),
    CREATOR_RISK_HISTORICAL_FUNDER_CLUSTER_MIN_RUG_CREATORS: Number(1),
    CREATOR_RISK_RELAY_FUNDING_ENABLED: false,
    CREATOR_RISK_RELAY_SIG_LIMIT: Number(8),
    CREATOR_RISK_RELAY_PARSED_TX_LIMIT: Number(6),
    CREATOR_RISK_RELAY_MIN_SOL: Number(20),
    CREATOR_RISK_RELAY_FORWARD_MIN_RATIO: Number(0.9),
    CREATOR_RISK_RELAY_WINDOW_SEC: Number(300),
    CREATOR_RISK_STANDARD_POOL_RELAY_BLOCK_ENABLED: false,
    CREATOR_RISK_STANDARD_POOL_TOLERANCE_SOL: Number(1.5),
    CREATOR_RISK_STANDARD_POOL_LEVELS_SOL: ("84.99,100,120").split(",").map((v) => Number(v.trim())).filter((v) => Number.isFinite(v) && v > 0),
    CREATOR_RISK_STANDARD_POOL_MICRO_BLOCK_ENABLED: true,
    CREATOR_RISK_STANDARD_POOL_MICRO_MIN_TRANSFERS: Number(4),
    CREATOR_RISK_STANDARD_POOL_MICRO_MIN_SOURCES: Number(2),
    CREATOR_RISK_STANDARD_POOL_MICRO_MAX_WINDOW_SEC: Number(30),
    CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_BLOCK_ENABLED: true,
    CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_MIN_COUNTERPARTIES: Number(18),
    CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_MIN_OUT_TRANSFERS: Number(18),
    CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_MAX_IN_TRANSFERS: Number(1),
    CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_MAX_WINDOW_SEC: Number(360),
    CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_BLOCK_ENABLED: false,
    CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_MIN_COUNTERPARTIES: Number(8),
    CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_MIN_OUT_TRANSFERS: Number(6),
    CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_MAX_MICRO_TRANSFERS: Number(4),
    CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_MIN_SOL: Number(150),
    CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_BLOCK_ENABLED: true,
    CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_MIN_COUNTERPARTIES: Number(8),
    CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_MIN_OUT_TRANSFERS: Number(7),
    CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_MAX_MICRO_TRANSFERS: Number(1),
    CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_MAX_MICRO_SOURCES: Number(1),
    CREATOR_RISK_SPRAY_OUTBOUND_BLOCK_ENABLED: true,
    CREATOR_RISK_SPRAY_OUTBOUND_MIN_TRANSFERS: Number(8),
    CREATOR_RISK_SPRAY_OUTBOUND_MIN_DESTINATIONS: Number(8),
    CREATOR_RISK_SPRAY_OUTBOUND_MAX_REL_STDDEV: Number(0.12),
    CREATOR_RISK_SPRAY_OUTBOUND_MAX_AMOUNT_RATIO: Number(1.25),
    CREATOR_RISK_INBOUND_SPRAY_BLOCK_ENABLED: true,
    CREATOR_RISK_INBOUND_SPRAY_MIN_TRANSFERS: Number(8),
    CREATOR_RISK_INBOUND_SPRAY_MIN_SOURCES: Number(8),
    CREATOR_RISK_INBOUND_SPRAY_MAX_REL_STDDEV: Number(0.12),
    CREATOR_RISK_INBOUND_SPRAY_MAX_AMOUNT_RATIO: Number(1.35),
    CREATOR_RISK_INBOUND_SPRAY_MAX_WINDOW_SEC: Number(30),
    CREATOR_RISK_SETUP_BURST_BLOCK_ENABLED: true,
    CREATOR_RISK_SETUP_BURST_MIN_CREATES: Number(250),
    CREATOR_RISK_SETUP_BURST_MAX_WINDOW_SEC: Number(90),
    CREATOR_RISK_CLOSE_ACCOUNT_BURST_BLOCK_ENABLED: true,
    CREATOR_RISK_CLOSE_ACCOUNT_BURST_MIN_TXS: Number(4),
    CREATOR_RISK_CLOSE_ACCOUNT_BURST_MIN_CLOSES: Number(12),
    CREATOR_RISK_CLOSE_ACCOUNT_BURST_MAX_WINDOW_SEC: Number(30),
    CREATOR_RISK_RAPID_DISPERSAL_BLOCK_ENABLED: true,
    CREATOR_RISK_RAPID_DISPERSAL_MIN_TRANSFERS: Number(3),
    CREATOR_RISK_RAPID_DISPERSAL_MIN_DESTINATIONS: Number(3),
    CREATOR_RISK_RAPID_DISPERSAL_MIN_TOTAL_SOL: Number(100),
    CREATOR_RISK_RAPID_DISPERSAL_MIN_PCT_OF_ENTRY_LIQ: Number(20),
    CREATOR_RISK_RAPID_DISPERSAL_MAX_WINDOW_SEC: Number(20),
    CREATOR_RISK_CREATOR_SEED_RATIO_BLOCK_ENABLED: false,
    CREATOR_RISK_CREATOR_SEED_MIN_PCT_OF_CURRENT_LIQ: Number(1),
    CREATOR_RISK_CREATOR_SEED_MAX_GROWTH_MULTIPLIER: Number(120),
    CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_BLOCK_ENABLED:
        true,
    CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_STRICT_FLOW_ENABLED:
        true,
    CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_MAX_FUNDING_AGE_SEC:
        Number(30),
    CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_MIN_FUNDING_SOL:
        Number(220),
    CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_MIN_SEED_SOL:
        Number(120),
    CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_MIN_SEED_PCT_OF_LIQ:
        Number(95),
    CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_MAX_COUNTERPARTIES:
        Number(3),
    CREATOR_RISK_MICRO_INBOUND_MAX_SOL: Number(0.001),
    CREATOR_RISK_MICRO_INBOUND_MIN_TRANSFERS: Number(6),
    CREATOR_RISK_MICRO_INBOUND_MIN_SOURCES: Number(2),
    CREATOR_RISK_MICRO_INBOUND_WINDOW_SEC: Number(5),
    CREATOR_RISK_DIRECT_AMM_REENTRY_ENABLED: false,
    CREATOR_RISK_DIRECT_AMM_REENTRY_SIG_LIMIT: Number(8),
    CREATOR_RISK_DIRECT_AMM_REENTRY_WINDOW_SEC: Number(180),
    CREATOR_RISK_PRECREATE_BURST_BLOCK_ENABLED: true,
    CREATOR_RISK_PRECREATE_BURST_WINDOW_SEC: Number(420),
    CREATOR_RISK_PRECREATE_BURST_SIG_LIMIT: Number(180),
    CREATOR_RISK_PRECREATE_BURST_PARSED_TX_LIMIT: Number(120),
    CREATOR_RISK_PRECREATE_BURST_MIN_TRANSFERS: Number(12),
    CREATOR_RISK_PRECREATE_BURST_MIN_DESTINATIONS: Number(12),
    CREATOR_RISK_PRECREATE_BURST_MIN_TRANSFER_SOL: Number(0.1),
    CREATOR_RISK_PRECREATE_BURST_MIN_TOTAL_SOL: Number(3),
    CREATOR_RISK_PRECREATE_BURST_MIN_MEDIAN_SOL: Number(0.1),
    CREATOR_RISK_PRECREATE_BURST_MAX_MEDIAN_SOL: Number(1.3),
    CREATOR_RISK_PRECREATE_BURST_MAX_REL_STDDEV: Number(0.18),
    CREATOR_RISK_PRECREATE_BURST_MAX_AMOUNT_RATIO: Number(1.6),
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_BLOCK_ENABLED:
        true,
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_MAX_WINDOW_SEC:
        Number(240),
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_MIN_TRANSFERS:
        Number(8),
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_MIN_DESTINATIONS:
        Number(8),
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_MIN_TRANSFER_SOL:
        Number(5),
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_MIN_TOTAL_SOL:
        Number(50),
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_MAX_REL_STDDEV:
        Number(0.12),
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_MAX_AMOUNT_RATIO:
        Number(1.6),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_BLOCK_ENABLED:
        true,
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MIN_TRANSFERS:
        Number(4),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MIN_DESTINATIONS:
        Number(4),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MIN_TRANSFER_SOL:
        Number(5),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MIN_TOTAL_SOL:
        Number(80),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MIN_MEDIAN_SOL:
        Number(20),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MAX_WINDOW_SEC:
        Number(90),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MIN_SETUP_CREATES:
        Number(20),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MAX_SETUP_WINDOW_SEC:
        Number(240),
    CREATOR_RISK_CONCENTRATED_INBOUND_BLOCK_ENABLED:
        true,
    CREATOR_RISK_CONCENTRATED_INBOUND_MAX_WINDOW_SEC:
        Number(240),
    CREATOR_RISK_CONCENTRATED_INBOUND_MIN_TRANSFERS:
        Number(12),
    CREATOR_RISK_CONCENTRATED_INBOUND_MAX_SOURCES:
        Number(3),
    CREATOR_RISK_CONCENTRATED_INBOUND_TOP_SOURCE_COUNT:
        Number(2),
    CREATOR_RISK_CONCENTRATED_INBOUND_MIN_TOP_SOURCE_SHARE:
        Number(0.85),
    CREATOR_RISK_CONCENTRATED_INBOUND_MIN_TRANSFER_SOL:
        Number(0.25),
    CREATOR_RISK_CONCENTRATED_INBOUND_MIN_TOTAL_SOL:
        Number(6),
    CREATOR_RISK_CONCENTRATED_INBOUND_MIN_MEDIAN_SOL:
        Number(0.25),
    CREATOR_RISK_CONCENTRATED_INBOUND_MAX_MEDIAN_SOL:
        Number(1.5),
    CREATOR_RISK_CONCENTRATED_INBOUND_MAX_REL_STDDEV:
        Number(0.35),
    CREATOR_RISK_CONCENTRATED_INBOUND_MAX_AMOUNT_RATIO:
        Number(4),
    CREATOR_RISK_CONCENTRATED_INBOUND_MIN_SETUP_CREATES:
        Number(8),
    CREATOR_RISK_CONCENTRATED_INBOUND_MIN_REPEAT_CREATES:
        Number(2),
    CREATOR_RISK_LOOKUP_TABLE_NEAR_CREATE_BLOCK_ENABLED:
        true,
    CREATOR_RISK_LOOKUP_TABLE_NEAR_CREATE_MAX_WINDOW_SEC:
        Number(30),
    CREATOR_RISK_LOOKUP_TABLE_NEAR_CREATE_MIN_LOOKUPS:
        Number(2),
    CREATOR_RISK_LOOKUP_TABLE_NEAR_CREATE_MIN_CREATES:
        Number(20),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_BLOCK_ENABLED: true,
    CREATOR_RISK_REPEAT_CREATE_REMOVE_WINDOW_SEC: Number(600),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_CREATES: Number(2),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_REMOVES: Number(1),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_CASHOUTS: Number(1),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_CREATE_SOL: Number(20),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_REMOVE_SOL: Number(20),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_CASHOUT_SOL: Number(2),
    HOLD_CREATOR_RISK_RECHECK_ENABLED: true,
    HOLD_CREATOR_RISK_RECHECK_INTERVAL_MS: Number(1500),
    CREATOR_RISK_FUNDER_REFUND_MIN_SOL: Number(0.05),
    HOLD_CREATOR_CASHOUT_EXIT_ENABLED: true,
    CREATOR_RISK_CASHOUT_ABS_SOL: Number(5),
    CREATOR_RISK_CASHOUT_REL_LIQ_PCT: Number(25),
    CREATOR_RISK_CASHOUT_WARN_SCORE: Number(0.5),
    CREATOR_RISK_CASHOUT_EXIT_SCORE: Number(1),
    SLIPPAGE_PERCENT: 20,
    REQUIRE_RENOUNCED_MINT: true,
    REQUIRE_NO_FREEZE: true,
    MAX_DEV_HOLDINGS_PCT: 20,
    ENFORCE_DEV_HOLDINGS_CHECK: true,
    DEV_HOLDINGS_MAX_ATTEMPTS: Number(3),
    DEV_HOLDINGS_RETRY_DELAY_MS: Number(250),
    DEV_HOLDINGS_MAX_DURATION_MS: Number(2000),
    LOG_STALE_RESUBSCRIBE_MS: 90000,
    HEALTHCHECK_INTERVAL_MS: 15000,
    SIGNATURE_CACHE_TTL_MS: 10 * 60 * 1000,
    SIGNATURE_CACHE_MAX_SIZE: 5000,
    SOL_PRICE_CACHE_TTL_MS: 30000,
    RUG_HISTORY_CACHE_TTL_MS: Number(60 * 1000),
    PAPER_TRADE_ENABLED: true,
    PAPER_CREATOR_RISK_PROBATION_ENABLED: false,
    PAPER_CREATOR_RISK_PROBATION_HOLD_MS: Number(15000),
    PAPER_CREATOR_CASHOUT_PROBATION_HOLD_MS: Number(45000),
    PAPER_CREATOR_RISK_EXTREME_CASHOUT_BLOCK_ENABLED: true,
    PAPER_CREATOR_RISK_EXTREME_CASHOUT_MIN_PCT_OF_LIQ: Number(95),
    PAPER_CREATOR_RISK_EXTREME_CASHOUT_MIN_SCORE: Number(25),
    PAPER_CREATOR_RISK_EXTREME_PROBATION_CASHOUT_BLOCK_ENABLED:
        true,
    PAPER_CREATOR_RISK_EXTREME_PROBATION_CASHOUT_MIN_SOL:
        Number(15),
    PAPER_CREATOR_RISK_EXTREME_PROBATION_CASHOUT_MIN_PCT_OF_LIQ:
        Number(15),
    PAPER_CREATOR_RISK_EXTREME_PROBATION_CASHOUT_MIN_SCORE:
        Number(4),
    PAPER_CREATOR_RISK_EXTREME_HISTORY_BLOCK_ENABLED:
        true,
    PAPER_CREATOR_RISK_EXTREME_HISTORY_MIN_COUNTERPARTIES:
        Number(100),
    PAPER_CREATOR_RISK_EXTREME_HISTORY_MIN_OUT_TRANSFERS:
        Number(100),
    PAPER_CREATOR_RISK_EXTREME_HISTORY_MAX_IN_TRANSFERS:
        Number(2),
    PAPER_CREATOR_RISK_EXTREME_UNIQUE_COUNTERPARTIES_BLOCK_ENABLED:
        true,
    PAPER_CREATOR_RISK_EXTREME_UNIQUE_COUNTERPARTIES_MIN:
        Number(100),
    PAPER_CREATOR_RISK_EXTREME_UNIQUE_COUNTERPARTIES_MIN_OUT_TRANSFERS:
        Number(100),
    PAPER_CREATOR_RISK_EXTREME_UNIQUE_COUNTERPARTIES_MAX_IN_TRANSFERS:
        Number(25),
    PAPER_CREATOR_RISK_PROBATION_UNIQUE_COUNTERPARTIES_BLOCK_ENABLED:
        true,
    PAPER_CREATOR_RISK_PROBATION_UNIQUE_COUNTERPARTIES_MIN:
        Number(28),
    PAPER_CREATOR_RISK_PROBATION_UNIQUE_COUNTERPARTIES_MIN_OUT_TRANSFERS:
        Number(28),
    PAPER_CREATOR_RISK_PROBATION_UNIQUE_COUNTERPARTIES_MAX_IN_TRANSFERS:
        Number(2),
    PAPER_CREATOR_RISK_PROBATION_LOW_CASHOUT_BLOCK_ENABLED:
        true,
    PAPER_CREATOR_RISK_PROBATION_LOW_CASHOUT_MIN_SOL:
        Number(3),
    PAPER_CREATOR_RISK_PROBATION_LOW_CASHOUT_MIN_PCT_OF_LIQ:
        Number(3),
    PAPER_CREATOR_RISK_PROBATION_LOW_CASHOUT_MIN_SCORE:
        Number(1),
    CREATOR_RESOLUTION_FAIL_OPEN: false,
    LOW_LIQUIDITY_RECHECK_ENABLED: true,
    LOW_LIQUIDITY_RECHECK_WINDOW_MS: Number(5000),
    LOW_LIQUIDITY_RECHECK_INTERVAL_MS: Number(300),
    LOW_LIQUIDITY_POOL_COOLDOWN_MS: Number(120000),
    MAX_CONCURRENT_OPERATIONS: Number(2),
    QUEUE_MAX_PENDING_SIGNATURES: Number(300),
    DEFERRED_NO_WSOL_QUEUE_ENABLED: false,
    DEFERRED_NO_WSOL_QUEUE_MAX_JOBS: Number(300),
    DEFERRED_NO_WSOL_INITIAL_DELAY_MS: Number(2000),
    DEFERRED_NO_WSOL_MAX_ATTEMPTS: Number(14),
    DEFERRED_NO_WSOL_BASE_INTERVAL_MS: Number(3000),
    DEFERRED_NO_WSOL_BACKOFF_MULTIPLIER: Number(1.5),
    DEFERRED_NO_WSOL_MAX_INTERVAL_MS: Number(30000),
    DEFERRED_NO_WSOL_MAX_AGE_MS: Number(300000),
    CC_SHADOW_ENABLED: false,
    CC_SHADOW_QUEUE_MAX_JOBS: Number(2000),
    CC_SHADOW_FAST_INTERVAL_MS: Number(5000),
    CC_SHADOW_FAST_PHASE_MS: Number(180000),
    CC_SHADOW_SLOW_INTERVAL_MS: Number(60000),
    CC_SHADOW_DEX_EVERY_N_SNAPSHOTS: Number(1),
    CREATOR_RISK_RATE_LIMIT_RETRIES: Number(3),
    CREATOR_RISK_RATE_LIMIT_RETRY_BASE_MS: Number(350),
    CREATOR_RISK_DEEP_CHECK_BUDGET_MS: Number(12000),
    CREATOR_RISK_RECHECK_DEEP_CHECK_BUDGET_MS: Number(2500),
    PAPER_TRADE_MAX_LOSS_PCT: Number(80),
} as const;

export const CONFIG_GROUPS = {
    preBuy: {
        waitMs: CONFIG.PRE_BUY_WAIT_MS,
        signalMinTrades: CONFIG.PRE_BUY_SIGNAL_MIN_TRADES,
        signalMinQuoteImprovementPct: CONFIG.PRE_BUY_SIGNAL_MIN_QUOTE_IMPROVEMENT_PCT,
        strictSignalMinQuoteImprovementPct: CONFIG.PRE_BUY_STRICT_SIGNAL_MIN_QUOTE_IMPROVEMENT_PCT,
        confirmSnapshots: CONFIG.PRE_BUY_CONFIRM_SNAPSHOTS,
        confirmIntervalMs: CONFIG.PRE_BUY_CONFIRM_INTERVAL_MS,
        noWsolRecheckEnabled: CONFIG.PRE_BUY_NO_WSOL_RECHECK_ENABLED,
        noWsolRecheckMaxAttempts: CONFIG.PRE_BUY_NO_WSOL_RECHECK_MAX_ATTEMPTS,
        noWsolRecheckIntervalMs: CONFIG.PRE_BUY_NO_WSOL_RECHECK_INTERVAL_MS,
        noWsolRecheckBackoffMultiplier: CONFIG.PRE_BUY_NO_WSOL_RECHECK_BACKOFF_MULTIPLIER,
        noWsolRecheckMaxIntervalMs: CONFIG.PRE_BUY_NO_WSOL_RECHECK_MAX_INTERVAL_MS,
        forceEntryOnNoWsolSide: CONFIG.FORCE_ENTRY_ON_NO_WSOL_SIDE,
        ultraShortRugGuardEnabled: CONFIG.PRE_BUY_ULTRA_SHORT_RUG_GUARD_ENABLED,
        ultraShortRugGuardWindowMs: CONFIG.PRE_BUY_ULTRA_SHORT_RUG_GUARD_WINDOW_MS,
        ultraShortRugGuardIntervalMs: CONFIG.PRE_BUY_ULTRA_SHORT_RUG_GUARD_INTERVAL_MS,
        ultraShortRugGuardMaxLiqDropPct: CONFIG.PRE_BUY_ULTRA_SHORT_RUG_GUARD_MAX_LIQ_DROP_PCT,
        ultraShortRugGuardMaxQuoteDropPct: CONFIG.PRE_BUY_ULTRA_SHORT_RUG_GUARD_MAX_QUOTE_DROP_PCT,
        revalidationEnabled: CONFIG.PRE_BUY_REVALIDATION_ENABLED,
        finalCreatorRiskRecheckEnabled: CONFIG.PRE_BUY_FINAL_CREATOR_RISK_RECHECK_ENABLED,
        finalRemoveLiqCheckEnabled: CONFIG.PRE_BUY_FINAL_REMOVE_LIQ_CHECK_ENABLED,
        top10CheckEnabled: CONFIG.PRE_BUY_TOP10_CHECK_ENABLED,
        top10MaxPct: CONFIG.PRE_BUY_TOP10_MAX_PCT,
        top10ExcludePool: CONFIG.PRE_BUY_TOP10_EXCLUDE_POOL,
        top1ExternalHolderCheckEnabled: CONFIG.PRE_BUY_TOP1_EXTERNAL_HOLDER_CHECK_ENABLED,
        top1ExternalHolderMaxPct: CONFIG.PRE_BUY_TOP1_EXTERNAL_HOLDER_MAX_PCT,
        top10FailOpen: CONFIG.PRE_BUY_TOP10_FAIL_OPEN,
    },
    hold: {
        autoSellDelayMs: CONFIG.AUTO_SELL_DELAY_MS,
        removeLiqDetectEnabled: CONFIG.HOLD_REMOVE_LIQ_DETECT_ENABLED,
        removeLiqCheckIntervalMs: CONFIG.HOLD_REMOVE_LIQ_CHECK_INTERVAL_MS,
        creatorRiskRecheckEnabled: CONFIG.HOLD_CREATOR_RISK_RECHECK_ENABLED,
        creatorRiskRecheckIntervalMs: CONFIG.HOLD_CREATOR_RISK_RECHECK_INTERVAL_MS,
        creatorCashoutExitEnabled: CONFIG.HOLD_CREATOR_CASHOUT_EXIT_ENABLED,
        suspiciousRelayShortHoldEnabled: CONFIG.HOLD_SUSPICIOUS_RELAY_SHORT_HOLD_ENABLED,
        suspiciousRelayShortHoldMs: CONFIG.HOLD_SUSPICIOUS_RELAY_SHORT_HOLD_MS,
        poolChurnDetectEnabled: CONFIG.HOLD_POOL_CHURN_DETECT_ENABLED,
        sellQuoteCollapseExitEnabled: CONFIG.HOLD_SELL_QUOTE_COLLAPSE_EXIT_ENABLED,
        singleSwapShockExitEnabled: CONFIG.HOLD_SINGLE_SWAP_SHOCK_EXIT_ENABLED,
        hardStopLossExitEnabled: CONFIG.HOLD_HARD_STOP_LOSS_EXIT_ENABLED,
        winnerManagementEnabled: CONFIG.HOLD_WINNER_MANAGEMENT_ENABLED,
    },
    creatorRisk: {
        enabled: CONFIG.CREATOR_RISK_CHECK_ENABLED,
        sigLimit: CONFIG.CREATOR_RISK_SIG_LIMIT,
        parsedTxLimit: CONFIG.CREATOR_RISK_PARSED_TX_LIMIT,
        maxUniqueCounterparties: CONFIG.CREATOR_RISK_MAX_UNIQUE_COUNTERPARTIES,
        relayFundingEnabled: CONFIG.CREATOR_RISK_RELAY_FUNDING_ENABLED,
        setupBurstBlockEnabled: CONFIG.CREATOR_RISK_SETUP_BURST_BLOCK_ENABLED,
        freshFundedHighSeedBlockEnabled: CONFIG.CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_BLOCK_ENABLED,
        directAmmReentryEnabled: CONFIG.CREATOR_RISK_DIRECT_AMM_REENTRY_ENABLED,
    },
    paper: {
        enabled: CONFIG.PAPER_TRADE_ENABLED,
        maxLossPct: CONFIG.PAPER_TRADE_MAX_LOSS_PCT,
        probationEnabled: CONFIG.PAPER_CREATOR_RISK_PROBATION_ENABLED,
        probationHoldMs: CONFIG.PAPER_CREATOR_RISK_PROBATION_HOLD_MS,
    },
    runtime: {
        maxConcurrentOperations: CONFIG.MAX_CONCURRENT_OPERATIONS,
        queueMaxPendingSignatures: CONFIG.QUEUE_MAX_PENDING_SIGNATURES,
        deferredNoWsolQueueEnabled: CONFIG.DEFERRED_NO_WSOL_QUEUE_ENABLED,
        deferredNoWsolQueueMaxJobs: CONFIG.DEFERRED_NO_WSOL_QUEUE_MAX_JOBS,
        deferredNoWsolInitialDelayMs: CONFIG.DEFERRED_NO_WSOL_INITIAL_DELAY_MS,
        deferredNoWsolMaxAttempts: CONFIG.DEFERRED_NO_WSOL_MAX_ATTEMPTS,
        deferredNoWsolBaseIntervalMs: CONFIG.DEFERRED_NO_WSOL_BASE_INTERVAL_MS,
        deferredNoWsolBackoffMultiplier: CONFIG.DEFERRED_NO_WSOL_BACKOFF_MULTIPLIER,
        deferredNoWsolMaxIntervalMs: CONFIG.DEFERRED_NO_WSOL_MAX_INTERVAL_MS,
        deferredNoWsolMaxAgeMs: CONFIG.DEFERRED_NO_WSOL_MAX_AGE_MS,
        ccShadowEnabled: CONFIG.CC_SHADOW_ENABLED,
        ccShadowQueueMaxJobs: CONFIG.CC_SHADOW_QUEUE_MAX_JOBS,
        ccShadowFastIntervalMs: CONFIG.CC_SHADOW_FAST_INTERVAL_MS,
        ccShadowFastPhaseMs: CONFIG.CC_SHADOW_FAST_PHASE_MS,
        ccShadowSlowIntervalMs: CONFIG.CC_SHADOW_SLOW_INTERVAL_MS,
        ccShadowDexEveryNSnapshots: CONFIG.CC_SHADOW_DEX_EVERY_N_SNAPSHOTS,
        lowLiquidityRecheckEnabled: CONFIG.LOW_LIQUIDITY_RECHECK_ENABLED,
        lowLiquidityRecheckWindowMs: CONFIG.LOW_LIQUIDITY_RECHECK_WINDOW_MS,
        lowLiquidityRecheckIntervalMs: CONFIG.LOW_LIQUIDITY_RECHECK_INTERVAL_MS,
    },
} as const;

export const PRE_BUY_CONFIG = CONFIG_GROUPS.preBuy;
export const HOLD_CONFIG = CONFIG_GROUPS.hold;
export const CREATOR_RISK_CONFIG = CONFIG_GROUPS.creatorRisk;
export const PAPER_CONFIG = CONFIG_GROUPS.paper;
export const RUNTIME_CONFIG = CONFIG_GROUPS.runtime;

export const DURING_TRADE_CONFIG = HOLD_CONFIG;

export const PHASE_CONFIG = {
    preBuy: PRE_BUY_CONFIG,
    duringTrade: DURING_TRADE_CONFIG,
    creatorRisk: CREATOR_RISK_CONFIG,
    paper: PAPER_CONFIG,
    runtime: RUNTIME_CONFIG,
} as const;

export const HOLD_WINNER_PROFILE: WinnerManagementProfile = {
    enabled: CONFIG.HOLD_WINNER_MANAGEMENT_ENABLED,
    checkIntervalMs: CONFIG.HOLD_WINNER_CHECK_INTERVAL_MS,
    minHoldMs: CONFIG.HOLD_WINNER_MIN_HOLD_MS,
    armPnlPct: CONFIG.HOLD_WINNER_ARM_PNL_PCT,
    trailingDropPct: CONFIG.HOLD_WINNER_TRAILING_DROP_PCT,
    hardTakeProfitPct: CONFIG.HOLD_WINNER_HARD_TAKE_PROFIT_PCT,
    minPeakSol: CONFIG.HOLD_WINNER_MIN_PEAK_SOL,
    profitFloorPct: CONFIG.HOLD_WINNER_PROFIT_FLOOR_PCT,
};
