import dotenv from "dotenv";
import { WinnerManagementProfile } from "../domain/types";

dotenv.config();


export const EARLY_ROOT_DIR = process.cwd();
export const IS_WORKER_PROCESS = !!process.env.WORKER_TASK_SIGNATURE;
export const WORKER_SLOT = Number(process.env.WORKER_SLOT || 0);
export const SILENCE_RPC_429_LOGS = process.env.SILENCE_RPC_429_LOGS !== "false";

function envBool(name: string, fallback: boolean): boolean {
    const raw = process.env[name];
    if (raw === undefined || raw === "") return fallback;
    return !["0", "false", "no", "off"].includes(raw.trim().toLowerCase());
}

export const CONFIG = {
    TRADE_AMOUNT_SOL: Number(process.env.TRADE_AMOUNT_SOL ?? 0.01),
    // Fee totale di pump sulla bonding curve, in basis point (protocollo + creator).
    // Misurata il 2026-09-12 su 1.111 TradeEvent reali: 95+30 = 125 bps nel 75% dei casi,
    // 0 bps nel 23%, 95+100 in coda. Si usa il caso dominante, che e anche il prudente.
    // Le fee sono dinamiche: se pump cambia il tariffario va rimisurata, non indovinata.
    PUMP_CURVE_FEE_BPS: Number(process.env.PUMP_CURVE_FEE_BPS || 125),
    MIN_POOL_LIQUIDITY_USD: Number(process.env.MIN_POOL_LIQUIDITY_USD || 10000),
    // Soglia via env perche e la prima leva da muovere quando si aggiunge un DEX: i pool
    // di ray_v4 e meteora_damm_v2 nascono con profondita diversa da quelli pumpswap.
    // Ogni trade logga entrySolLiquidity, quindi i risultati restano segmentabili per fascia.
    MIN_POOL_LIQUIDITY_SOL: Number(process.env.MIN_POOL_LIQUIDITY_SOL || 20),
    AUTO_SELL_DELAY_MS: Number(process.env.AUTO_SELL_DELAY_MS ?? 900000),
    HOLD_SUSPICIOUS_RELAY_SHORT_HOLD_ENABLED: envBool("HOLD_SUSPICIOUS_RELAY_SHORT_HOLD_ENABLED", true),
    HOLD_SUSPICIOUS_RELAY_SHORT_HOLD_MS: Number(process.env.HOLD_SUSPICIOUS_RELAY_SHORT_HOLD_MS ?? 15000),
    HOLD_REMOVE_LIQ_DETECT_ENABLED: envBool("HOLD_REMOVE_LIQ_DETECT_ENABLED", true),
    HOLD_REMOVE_LIQ_CHECK_INTERVAL_MS: Number(process.env.HOLD_REMOVE_LIQ_CHECK_INTERVAL_MS ?? 1500),
    HOLD_REMOVE_LIQ_MIN_WSOL_TO_CREATOR: Number(process.env.HOLD_REMOVE_LIQ_MIN_WSOL_TO_CREATOR ?? 0.5),
    HOLD_REMOVE_LIQ_MIN_SOL_TO_CREATOR: Number(process.env.HOLD_REMOVE_LIQ_MIN_SOL_TO_CREATOR ?? 0.5),
    HOLD_CREATOR_AMM_BURST_DETECT_ENABLED: envBool("HOLD_CREATOR_AMM_BURST_DETECT_ENABLED", true),
    HOLD_CREATOR_AMM_BURST_WINDOW_SEC: Number(process.env.HOLD_CREATOR_AMM_BURST_WINDOW_SEC ?? 8),
    HOLD_CREATOR_AMM_BURST_MIN_TXS: Number(process.env.HOLD_CREATOR_AMM_BURST_MIN_TXS ?? 3),
    HOLD_CREATOR_OUTBOUND_EXIT_ENABLED: envBool("HOLD_CREATOR_OUTBOUND_EXIT_ENABLED", true),
    HOLD_CREATOR_OUTBOUND_CHECK_INTERVAL_MS: Number(process.env.HOLD_CREATOR_OUTBOUND_CHECK_INTERVAL_MS ?? 1500),
    HOLD_CREATOR_OUTBOUND_MIN_SOL: Number(process.env.HOLD_CREATOR_OUTBOUND_MIN_SOL ?? 10),
    HOLD_CREATOR_CLOSE_ACCOUNT_BURST_EXIT_ENABLED: envBool("HOLD_CREATOR_CLOSE_ACCOUNT_BURST_EXIT_ENABLED", true),
    HOLD_CREATOR_CLOSE_ACCOUNT_BURST_CHECK_INTERVAL_MS: Number(process.env.HOLD_CREATOR_CLOSE_ACCOUNT_BURST_CHECK_INTERVAL_MS ?? 1000),
    HOLD_CREATOR_CLOSE_ACCOUNT_BURST_WINDOW_SEC: Number(process.env.HOLD_CREATOR_CLOSE_ACCOUNT_BURST_WINDOW_SEC ?? 20),
    HOLD_CREATOR_CLOSE_ACCOUNT_BURST_MIN_TXS: Number(process.env.HOLD_CREATOR_CLOSE_ACCOUNT_BURST_MIN_TXS ?? 3),
    HOLD_CREATOR_CLOSE_ACCOUNT_BURST_MIN_CLOSES: Number(process.env.HOLD_CREATOR_CLOSE_ACCOUNT_BURST_MIN_CLOSES ?? 12),
    HOLD_CREATOR_OUTBOUND_SPRAY_EXIT_ENABLED: envBool("HOLD_CREATOR_OUTBOUND_SPRAY_EXIT_ENABLED", true),
    HOLD_CREATOR_OUTBOUND_SPRAY_CHECK_INTERVAL_MS: Number(process.env.HOLD_CREATOR_OUTBOUND_SPRAY_CHECK_INTERVAL_MS ?? 1500),
    HOLD_CREATOR_OUTBOUND_SPRAY_WINDOW_SEC: Number(process.env.HOLD_CREATOR_OUTBOUND_SPRAY_WINDOW_SEC ?? 30),
    HOLD_CREATOR_OUTBOUND_SPRAY_MIN_TRANSFERS: Number(process.env.HOLD_CREATOR_OUTBOUND_SPRAY_MIN_TRANSFERS ?? 20),
    HOLD_CREATOR_OUTBOUND_SPRAY_MIN_DESTINATIONS: Number(process.env.HOLD_CREATOR_OUTBOUND_SPRAY_MIN_DESTINATIONS ?? 20),
    HOLD_CREATOR_OUTBOUND_SPRAY_MAX_MEDIAN_SOL: Number(process.env.HOLD_CREATOR_OUTBOUND_SPRAY_MAX_MEDIAN_SOL ?? 0.05),
    HOLD_CREATOR_OUTBOUND_SPRAY_MAX_REL_STDDEV: Number(process.env.HOLD_CREATOR_OUTBOUND_SPRAY_MAX_REL_STDDEV ?? 0.2),
    HOLD_CREATOR_OUTBOUND_SPRAY_MAX_AMOUNT_RATIO: Number(process.env.HOLD_CREATOR_OUTBOUND_SPRAY_MAX_AMOUNT_RATIO ?? 3),
    HOLD_CREATOR_INBOUND_SPRAY_EXIT_ENABLED: envBool("HOLD_CREATOR_INBOUND_SPRAY_EXIT_ENABLED", true),
    HOLD_CREATOR_INBOUND_SPRAY_CHECK_INTERVAL_MS: Number(process.env.HOLD_CREATOR_INBOUND_SPRAY_CHECK_INTERVAL_MS ?? 1500),
    HOLD_CREATOR_INBOUND_SPRAY_WINDOW_SEC: Number(process.env.HOLD_CREATOR_INBOUND_SPRAY_WINDOW_SEC ?? 30),
    HOLD_CREATOR_INBOUND_SPRAY_MIN_TRANSFERS: Number(process.env.HOLD_CREATOR_INBOUND_SPRAY_MIN_TRANSFERS ?? 8),
    HOLD_CREATOR_INBOUND_SPRAY_MIN_SOURCES: Number(process.env.HOLD_CREATOR_INBOUND_SPRAY_MIN_SOURCES ?? 8),
    HOLD_CREATOR_INBOUND_SPRAY_MAX_REL_STDDEV: Number(process.env.HOLD_CREATOR_INBOUND_SPRAY_MAX_REL_STDDEV ?? 0.12),
    HOLD_CREATOR_INBOUND_SPRAY_MAX_AMOUNT_RATIO: Number(process.env.HOLD_CREATOR_INBOUND_SPRAY_MAX_AMOUNT_RATIO ?? 1.35),
    HOLD_POOL_CHURN_DETECT_ENABLED: envBool("HOLD_POOL_CHURN_DETECT_ENABLED", true),
    HOLD_POOL_CHURN_CHECK_INTERVAL_MS: Number(process.env.HOLD_POOL_CHURN_CHECK_INTERVAL_MS ?? 1500),
    HOLD_POOL_CHURN_SIG_LIMIT: Number(process.env.HOLD_POOL_CHURN_SIG_LIMIT ?? 60),
    HOLD_POOL_CHURN_WINDOW_SHORT_MS: Number(process.env.HOLD_POOL_CHURN_WINDOW_SHORT_MS ?? 10000),
    HOLD_POOL_CHURN_WINDOW_LONG_MS: Number(process.env.HOLD_POOL_CHURN_WINDOW_LONG_MS ?? 20000),
    HOLD_POOL_CHURN_WINDOW_CRITICAL_MS: Number(process.env.HOLD_POOL_CHURN_WINDOW_CRITICAL_MS ?? 40000),
    HOLD_POOL_CHURN_TX_SHORT_MIN: Number(process.env.HOLD_POOL_CHURN_TX_SHORT_MIN ?? 10),
    HOLD_POOL_CHURN_TX_LONG_MIN: Number(process.env.HOLD_POOL_CHURN_TX_LONG_MIN ?? 20),
    HOLD_POOL_CHURN_TX_CRITICAL_MIN: Number(process.env.HOLD_POOL_CHURN_TX_CRITICAL_MIN ?? 30),
    HOLD_POOL_CHURN_SELL_DROP_PCT: Number(process.env.HOLD_POOL_CHURN_SELL_DROP_PCT ?? 50),
    HOLD_POOL_CHURN_CRITICAL_SELL_DROP_PCT: Number(process.env.HOLD_POOL_CHURN_CRITICAL_SELL_DROP_PCT ?? 35),
    HOLD_SELL_QUOTE_COLLAPSE_EXIT_ENABLED: envBool("HOLD_SELL_QUOTE_COLLAPSE_EXIT_ENABLED", true),
    HOLD_SELL_QUOTE_COLLAPSE_CHECK_INTERVAL_MS: Number(process.env.HOLD_SELL_QUOTE_COLLAPSE_CHECK_INTERVAL_MS ?? 300),
    HOLD_SELL_QUOTE_COLLAPSE_MIN_HOLD_MS: Number(process.env.HOLD_SELL_QUOTE_COLLAPSE_MIN_HOLD_MS ?? 3000),
    HOLD_SELL_QUOTE_COLLAPSE_DROP_PCT: Number(process.env.HOLD_SELL_QUOTE_COLLAPSE_DROP_PCT ?? 35),
    HOLD_SELL_QUOTE_COLLAPSE_MIN_SOL: Number(process.env.HOLD_SELL_QUOTE_COLLAPSE_MIN_SOL ?? 0.0025),
    HOLD_SINGLE_SWAP_SHOCK_EXIT_ENABLED: envBool("HOLD_SINGLE_SWAP_SHOCK_EXIT_ENABLED", true),
    HOLD_SINGLE_SWAP_SHOCK_CHECK_INTERVAL_MS: Number(process.env.HOLD_SINGLE_SWAP_SHOCK_CHECK_INTERVAL_MS ?? 300),
    HOLD_SINGLE_SWAP_SHOCK_MIN_HOLD_MS: Number(process.env.HOLD_SINGLE_SWAP_SHOCK_MIN_HOLD_MS ?? 3000),
    HOLD_SINGLE_SWAP_SHOCK_DROP_PCT: Number(process.env.HOLD_SINGLE_SWAP_SHOCK_DROP_PCT ?? 35),
    HOLD_HARD_STOP_LOSS_EXIT_ENABLED: envBool("HOLD_HARD_STOP_LOSS_EXIT_ENABLED", true),
    HOLD_HARD_STOP_LOSS_CHECK_INTERVAL_MS: Number(process.env.HOLD_HARD_STOP_LOSS_CHECK_INTERVAL_MS ?? 250),
    HOLD_HARD_STOP_LOSS_MIN_HOLD_MS: Number(process.env.HOLD_HARD_STOP_LOSS_MIN_HOLD_MS ?? 3000),
    HOLD_HARD_STOP_LOSS_PCT: Number(process.env.HOLD_HARD_STOP_LOSS_PCT ?? 15),
    HOLD_WINNER_MANAGEMENT_ENABLED: envBool("HOLD_WINNER_MANAGEMENT_ENABLED", true),
    HOLD_WINNER_CHECK_INTERVAL_MS: Number(process.env.HOLD_WINNER_CHECK_INTERVAL_MS ?? 200),
    HOLD_WINNER_MIN_HOLD_MS: Number(process.env.HOLD_WINNER_MIN_HOLD_MS ?? 4000),
    HOLD_WINNER_ARM_PNL_PCT: Number(process.env.HOLD_WINNER_ARM_PNL_PCT ?? 8),
    HOLD_WINNER_TRAILING_DROP_PCT: Number(process.env.HOLD_WINNER_TRAILING_DROP_PCT ?? 10),
    HOLD_WINNER_TRAILING_DROP_PCT_CP0: Number(process.env.HOLD_WINNER_TRAILING_DROP_PCT_CP0 ?? 10),
    HOLD_WINNER_HARD_TAKE_PROFIT_PCT: Number(process.env.HOLD_WINNER_HARD_TAKE_PROFIT_PCT ?? 50),
    HOLD_WINNER_HARD_TAKE_PROFIT_PCT_CP1: Number(process.env.HOLD_WINNER_HARD_TAKE_PROFIT_PCT_CP1 ?? 50),
    HOLD_WINNER_MIN_PEAK_SOL: Number(process.env.HOLD_WINNER_MIN_PEAK_SOL ?? 0.0104),
    HOLD_WINNER_PROFIT_FLOOR_PCT: Number(process.env.HOLD_WINNER_PROFIT_FLOOR_PCT ?? 3),
    // Price path recorder: campiona il quote di uscita durante l'hold per rendere
    // le sessioni paper ri-simulabili offline (trailing, floor, exit anticipate).
    HOLD_PRICE_PATH_RECORD_ENABLED: envBool("HOLD_PRICE_PATH_RECORD_ENABLED", true),
    HOLD_PRICE_PATH_MAX_SAMPLES: Number(process.env.HOLD_PRICE_PATH_MAX_SAMPLES || 3000),
    HOLD_PRICE_PATH_MIN_CHANGE_PCT: Number(process.env.HOLD_PRICE_PATH_MIN_CHANGE_PCT ?? 0.05),
    HOLD_PRICE_PATH_HEARTBEAT_MS: Number(process.env.HOLD_PRICE_PATH_HEARTBEAT_MS || 5000),
    HOLD_PROBATION_CASHOUT_DELTA_MIN_SOL: Number(process.env.HOLD_PROBATION_CASHOUT_DELTA_MIN_SOL ?? 5),
    HOLD_PROBATION_INTERVAL_MULTIPLIER: Number(process.env.HOLD_PROBATION_INTERVAL_MULTIPLIER ?? 0.4),
    PRE_BUY_REVALIDATION_ENABLED: envBool("PRE_BUY_REVALIDATION_ENABLED", true),
    PRE_BUY_FINAL_CREATOR_RISK_RECHECK_ENABLED: envBool("PRE_BUY_FINAL_CREATOR_RISK_RECHECK_ENABLED", true),
    PRE_BUY_FINAL_REMOVE_LIQ_CHECK_ENABLED: envBool("PRE_BUY_FINAL_REMOVE_LIQ_CHECK_ENABLED", true),
    PRE_BUY_REVALIDATION_MAX_LIQ_DROP_PCT: Number(process.env.PRE_BUY_REVALIDATION_MAX_LIQ_DROP_PCT ?? 35),
    PRE_BUY_REVALIDATION_MAX_QUOTE_VS_SPOT_RATIO: Number(process.env.PRE_BUY_REVALIDATION_MAX_QUOTE_VS_SPOT_RATIO ?? 25),
    PRE_BUY_WAIT_MS: Number(process.env.PRE_BUY_WAIT_MS ?? 1500),
    PRE_BUY_SIGNAL_MIN_TRADES: Number(process.env.PRE_BUY_SIGNAL_MIN_TRADES ?? 10),
    PRE_BUY_SIGNAL_MIN_QUOTE_IMPROVEMENT_PCT: Number(process.env.PRE_BUY_SIGNAL_MIN_QUOTE_IMPROVEMENT_PCT ?? 0),
    PRE_BUY_STRICT_SIGNAL_MIN_QUOTE_IMPROVEMENT_PCT: Number(process.env.PRE_BUY_STRICT_SIGNAL_MIN_QUOTE_IMPROVEMENT_PCT ?? 0.25),
    PRE_BUY_MAX_LIQ_DROP_PCT: Number(process.env.PRE_BUY_MAX_LIQ_DROP_PCT ?? 10),
    PRE_BUY_CONFIRM_SNAPSHOTS: Number(process.env.PRE_BUY_CONFIRM_SNAPSHOTS ?? 3),
    PRE_BUY_CONFIRM_INTERVAL_MS: Number(process.env.PRE_BUY_CONFIRM_INTERVAL_MS ?? 350),
    PRE_BUY_NO_WSOL_RECHECK_ENABLED: envBool("PRE_BUY_NO_WSOL_RECHECK_ENABLED", true),
    PRE_BUY_NO_WSOL_RECHECK_MAX_ATTEMPTS: Number(process.env.PRE_BUY_NO_WSOL_RECHECK_MAX_ATTEMPTS ?? 10),
    PRE_BUY_NO_WSOL_RECHECK_INTERVAL_MS: Number(process.env.PRE_BUY_NO_WSOL_RECHECK_INTERVAL_MS ?? 350),
    PRE_BUY_NO_WSOL_RECHECK_BACKOFF_MULTIPLIER: Number(process.env.PRE_BUY_NO_WSOL_RECHECK_BACKOFF_MULTIPLIER ?? 1.35),
    PRE_BUY_NO_WSOL_RECHECK_MAX_INTERVAL_MS: Number(process.env.PRE_BUY_NO_WSOL_RECHECK_MAX_INTERVAL_MS ?? 1200),
    FORCE_ENTRY_ON_NO_WSOL_SIDE: envBool("FORCE_ENTRY_ON_NO_WSOL_SIDE", false),
    PRE_BUY_ULTRA_SHORT_RUG_GUARD_ENABLED: envBool("PRE_BUY_ULTRA_SHORT_RUG_GUARD_ENABLED", true),
    PRE_BUY_ULTRA_SHORT_RUG_GUARD_WINDOW_MS: Number(process.env.PRE_BUY_ULTRA_SHORT_RUG_GUARD_WINDOW_MS ?? 2500),
    PRE_BUY_ULTRA_SHORT_RUG_GUARD_INTERVAL_MS: Number(process.env.PRE_BUY_ULTRA_SHORT_RUG_GUARD_INTERVAL_MS ?? 500),
    PRE_BUY_ULTRA_SHORT_RUG_GUARD_MAX_LIQ_DROP_PCT: Number(process.env.PRE_BUY_ULTRA_SHORT_RUG_GUARD_MAX_LIQ_DROP_PCT ?? 35),
    PRE_BUY_ULTRA_SHORT_RUG_GUARD_MAX_QUOTE_DROP_PCT: Number(process.env.PRE_BUY_ULTRA_SHORT_RUG_GUARD_MAX_QUOTE_DROP_PCT ?? 35),
    PRE_BUY_TOP10_CHECK_ENABLED: envBool("PRE_BUY_TOP10_CHECK_ENABLED", true),
    PRE_BUY_TOP10_MAX_PCT: Number(process.env.PRE_BUY_TOP10_MAX_PCT ?? 90),
    PRE_BUY_TOP10_EXCLUDE_POOL: envBool("PRE_BUY_TOP10_EXCLUDE_POOL", true),
    PRE_BUY_TOP1_EXTERNAL_HOLDER_CHECK_ENABLED: envBool("PRE_BUY_TOP1_EXTERNAL_HOLDER_CHECK_ENABLED", true),
    PRE_BUY_TOP1_EXTERNAL_HOLDER_MAX_PCT: Number(process.env.PRE_BUY_TOP1_EXTERNAL_HOLDER_MAX_PCT ?? 20),
    PRE_BUY_TOP10_FAIL_OPEN: envBool("PRE_BUY_TOP10_FAIL_OPEN", false),
    PRE_BUY_TOP10_MAX_ATTEMPTS: Number(process.env.PRE_BUY_TOP10_MAX_ATTEMPTS ?? 4),
    // Tetto a orologio sull'intero controllo top-10. I tentativi da soli non bastano: con
    // 4 giri x 8 tentativi interni x 8s di timeout il caso peggiore e oltre 4 minuti di slot
    // worker occupato per un controllo che, su un token appena nato, ha 2 holder.
    PRE_BUY_TOP10_MAX_TOTAL_MS: Number(process.env.PRE_BUY_TOP10_MAX_TOTAL_MS || 20000),
    PRE_BUY_TOP10_RETRY_BASE_MS: Number(process.env.PRE_BUY_TOP10_RETRY_BASE_MS ?? 400),
    CREATOR_RISK_CHECK_ENABLED: envBool("CREATOR_RISK_CHECK_ENABLED", true),
    CREATOR_RISK_SIG_LIMIT: Number(process.env.CREATOR_RISK_SIG_LIMIT ?? 80),
    CREATOR_RISK_PARSED_TX_LIMIT: Number(process.env.CREATOR_RISK_PARSED_TX_LIMIT ?? 50),
    CREATOR_RISK_CACHE_TTL_MS: Number(process.env.CREATOR_RISK_CACHE_TTL_MS ?? 15 * 60 * 1000),
    CREATOR_RISK_MAX_UNIQUE_COUNTERPARTIES: Number(process.env.CREATOR_RISK_MAX_UNIQUE_COUNTERPARTIES ?? 3),
    CREATOR_RISK_WHITELISTED_CC_VALUES: (process.env.CREATOR_RISK_WHITELISTED_CC_VALUES || "0,2,4,47")
        .split(",")
        .map((v) => Number(v.trim()))
        .filter((v) => Number.isFinite(v) && v >= 0),
    CREATOR_RISK_COMPRESSED_MAX_COUNTERPARTIES: Number(process.env.CREATOR_RISK_COMPRESSED_MAX_COUNTERPARTIES ?? 60),
    CREATOR_RISK_COMPRESSED_WINDOW_SEC: Number(process.env.CREATOR_RISK_COMPRESSED_WINDOW_SEC ?? 90),
    CREATOR_RISK_BURNER_MIN_OUT_SOL: Number(process.env.CREATOR_RISK_BURNER_MIN_OUT_SOL ?? 100),
    CREATOR_RISK_FUNDER_CLUSTER_ENABLED: envBool("CREATOR_RISK_FUNDER_CLUSTER_ENABLED", true),
    CREATOR_RISK_FUNDER_CLUSTER_MIN_CREATORS: Number(process.env.CREATOR_RISK_FUNDER_CLUSTER_MIN_CREATORS ?? 2),
    CREATOR_RISK_FUNDER_CLUSTER_WINDOW_SEC: Number(process.env.CREATOR_RISK_FUNDER_CLUSTER_WINDOW_SEC ?? 900),
    CREATOR_RISK_HISTORICAL_FUNDER_CLUSTER_MIN_RUG_CREATORS: Number(process.env.CREATOR_RISK_HISTORICAL_FUNDER_CLUSTER_MIN_RUG_CREATORS ?? 1),
    CREATOR_RISK_RELAY_FUNDING_ENABLED: envBool("CREATOR_RISK_RELAY_FUNDING_ENABLED", false),
    CREATOR_RISK_RELAY_SIG_LIMIT: Number(process.env.CREATOR_RISK_RELAY_SIG_LIMIT ?? 8),
    CREATOR_RISK_RELAY_PARSED_TX_LIMIT: Number(process.env.CREATOR_RISK_RELAY_PARSED_TX_LIMIT ?? 6),
    CREATOR_RISK_RELAY_MIN_SOL: Number(process.env.CREATOR_RISK_RELAY_MIN_SOL ?? 20),
    CREATOR_RISK_RELAY_FORWARD_MIN_RATIO: Number(process.env.CREATOR_RISK_RELAY_FORWARD_MIN_RATIO ?? 0.9),
    CREATOR_RISK_RELAY_WINDOW_SEC: Number(process.env.CREATOR_RISK_RELAY_WINDOW_SEC ?? 300),
    CREATOR_RISK_STANDARD_POOL_RELAY_BLOCK_ENABLED: envBool("CREATOR_RISK_STANDARD_POOL_RELAY_BLOCK_ENABLED", false),
    CREATOR_RISK_STANDARD_POOL_TOLERANCE_SOL: Number(process.env.CREATOR_RISK_STANDARD_POOL_TOLERANCE_SOL ?? 1.5),
    CREATOR_RISK_STANDARD_POOL_LEVELS_SOL: ("84.99,100,120").split(",").map((v) => Number(v.trim())).filter((v) => Number.isFinite(v) && v > 0),
    CREATOR_RISK_STANDARD_POOL_MICRO_BLOCK_ENABLED: envBool("CREATOR_RISK_STANDARD_POOL_MICRO_BLOCK_ENABLED", true),
    CREATOR_RISK_STANDARD_POOL_MICRO_MIN_TRANSFERS: Number(process.env.CREATOR_RISK_STANDARD_POOL_MICRO_MIN_TRANSFERS ?? 4),
    CREATOR_RISK_STANDARD_POOL_MICRO_MIN_SOURCES: Number(process.env.CREATOR_RISK_STANDARD_POOL_MICRO_MIN_SOURCES ?? 2),
    CREATOR_RISK_STANDARD_POOL_MICRO_MAX_WINDOW_SEC: Number(process.env.CREATOR_RISK_STANDARD_POOL_MICRO_MAX_WINDOW_SEC ?? 30),
    CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_BLOCK_ENABLED: envBool("CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_BLOCK_ENABLED", true),
    CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_MIN_COUNTERPARTIES: Number(process.env.CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_MIN_COUNTERPARTIES ?? 18),
    CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_MIN_OUT_TRANSFERS: Number(process.env.CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_MIN_OUT_TRANSFERS ?? 18),
    CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_MAX_IN_TRANSFERS: Number(process.env.CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_MAX_IN_TRANSFERS ?? 1),
    CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_MAX_WINDOW_SEC: Number(process.env.CREATOR_RISK_STANDARD_POOL_OUTBOUND_HEAVY_MAX_WINDOW_SEC ?? 360),
    CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_BLOCK_ENABLED: envBool("CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_BLOCK_ENABLED", false),
    CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_MIN_COUNTERPARTIES: Number(process.env.CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_MIN_COUNTERPARTIES ?? 8),
    CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_MIN_OUT_TRANSFERS: Number(process.env.CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_MIN_OUT_TRANSFERS ?? 6),
    CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_MAX_MICRO_TRANSFERS: Number(process.env.CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_MAX_MICRO_TRANSFERS ?? 4),
    CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_MIN_SOL: Number(process.env.CREATOR_RISK_STANDARD_POOL_RELAY_OUTBOUND_MIN_SOL ?? 150),
    CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_BLOCK_ENABLED: envBool("CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_BLOCK_ENABLED", true),
    CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_MIN_COUNTERPARTIES: Number(process.env.CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_MIN_COUNTERPARTIES ?? 8),
    CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_MIN_OUT_TRANSFERS: Number(process.env.CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_MIN_OUT_TRANSFERS ?? 7),
    CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_MAX_MICRO_TRANSFERS: Number(process.env.CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_MAX_MICRO_TRANSFERS ?? 1),
    CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_MAX_MICRO_SOURCES: Number(process.env.CREATOR_RISK_SUSPICIOUS_ROOT_PATTERN_MAX_MICRO_SOURCES ?? 1),
    CREATOR_RISK_SPRAY_OUTBOUND_BLOCK_ENABLED: envBool("CREATOR_RISK_SPRAY_OUTBOUND_BLOCK_ENABLED", true),
    CREATOR_RISK_SPRAY_OUTBOUND_MIN_TRANSFERS: Number(process.env.CREATOR_RISK_SPRAY_OUTBOUND_MIN_TRANSFERS ?? 8),
    CREATOR_RISK_SPRAY_OUTBOUND_MIN_DESTINATIONS: Number(process.env.CREATOR_RISK_SPRAY_OUTBOUND_MIN_DESTINATIONS ?? 8),
    CREATOR_RISK_SPRAY_OUTBOUND_MAX_REL_STDDEV: Number(process.env.CREATOR_RISK_SPRAY_OUTBOUND_MAX_REL_STDDEV ?? 0.12),
    CREATOR_RISK_SPRAY_OUTBOUND_MAX_AMOUNT_RATIO: Number(process.env.CREATOR_RISK_SPRAY_OUTBOUND_MAX_AMOUNT_RATIO ?? 1.25),
    CREATOR_RISK_INBOUND_SPRAY_BLOCK_ENABLED: envBool("CREATOR_RISK_INBOUND_SPRAY_BLOCK_ENABLED", true),
    CREATOR_RISK_INBOUND_SPRAY_MIN_TRANSFERS: Number(process.env.CREATOR_RISK_INBOUND_SPRAY_MIN_TRANSFERS ?? 8),
    CREATOR_RISK_INBOUND_SPRAY_MIN_SOURCES: Number(process.env.CREATOR_RISK_INBOUND_SPRAY_MIN_SOURCES ?? 8),
    CREATOR_RISK_INBOUND_SPRAY_MAX_REL_STDDEV: Number(process.env.CREATOR_RISK_INBOUND_SPRAY_MAX_REL_STDDEV ?? 0.12),
    CREATOR_RISK_INBOUND_SPRAY_MAX_AMOUNT_RATIO: Number(process.env.CREATOR_RISK_INBOUND_SPRAY_MAX_AMOUNT_RATIO ?? 1.35),
    CREATOR_RISK_INBOUND_SPRAY_MAX_WINDOW_SEC: Number(process.env.CREATOR_RISK_INBOUND_SPRAY_MAX_WINDOW_SEC ?? 30),
    CREATOR_RISK_SETUP_BURST_BLOCK_ENABLED: envBool("CREATOR_RISK_SETUP_BURST_BLOCK_ENABLED", true),
    CREATOR_RISK_SETUP_BURST_MIN_CREATES: Number(process.env.CREATOR_RISK_SETUP_BURST_MIN_CREATES ?? 250),
    CREATOR_RISK_SETUP_BURST_MAX_WINDOW_SEC: Number(process.env.CREATOR_RISK_SETUP_BURST_MAX_WINDOW_SEC ?? 90),
    CREATOR_RISK_CLOSE_ACCOUNT_BURST_BLOCK_ENABLED: envBool("CREATOR_RISK_CLOSE_ACCOUNT_BURST_BLOCK_ENABLED", true),
    CREATOR_RISK_CLOSE_ACCOUNT_BURST_MIN_TXS: Number(process.env.CREATOR_RISK_CLOSE_ACCOUNT_BURST_MIN_TXS ?? 4),
    CREATOR_RISK_CLOSE_ACCOUNT_BURST_MIN_CLOSES: Number(process.env.CREATOR_RISK_CLOSE_ACCOUNT_BURST_MIN_CLOSES ?? 12),
    CREATOR_RISK_CLOSE_ACCOUNT_BURST_MAX_WINDOW_SEC: Number(process.env.CREATOR_RISK_CLOSE_ACCOUNT_BURST_MAX_WINDOW_SEC ?? 30),
    CREATOR_RISK_RAPID_DISPERSAL_BLOCK_ENABLED: envBool("CREATOR_RISK_RAPID_DISPERSAL_BLOCK_ENABLED", true),
    CREATOR_RISK_RAPID_DISPERSAL_MIN_TRANSFERS: Number(process.env.CREATOR_RISK_RAPID_DISPERSAL_MIN_TRANSFERS ?? 3),
    CREATOR_RISK_RAPID_DISPERSAL_MIN_DESTINATIONS: Number(process.env.CREATOR_RISK_RAPID_DISPERSAL_MIN_DESTINATIONS ?? 3),
    CREATOR_RISK_RAPID_DISPERSAL_MIN_TOTAL_SOL: Number(process.env.CREATOR_RISK_RAPID_DISPERSAL_MIN_TOTAL_SOL ?? 100),
    CREATOR_RISK_RAPID_DISPERSAL_MIN_PCT_OF_ENTRY_LIQ: Number(process.env.CREATOR_RISK_RAPID_DISPERSAL_MIN_PCT_OF_ENTRY_LIQ ?? 20),
    CREATOR_RISK_RAPID_DISPERSAL_MAX_WINDOW_SEC: Number(process.env.CREATOR_RISK_RAPID_DISPERSAL_MAX_WINDOW_SEC ?? 20),
    CREATOR_RISK_CREATOR_SEED_RATIO_BLOCK_ENABLED: envBool("CREATOR_RISK_CREATOR_SEED_RATIO_BLOCK_ENABLED", false),
    CREATOR_RISK_CREATOR_SEED_MIN_PCT_OF_CURRENT_LIQ: Number(process.env.CREATOR_RISK_CREATOR_SEED_MIN_PCT_OF_CURRENT_LIQ ?? 1),
    CREATOR_RISK_CREATOR_SEED_MAX_GROWTH_MULTIPLIER: Number(process.env.CREATOR_RISK_CREATOR_SEED_MAX_GROWTH_MULTIPLIER ?? 120),
    CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_BLOCK_ENABLED:
        true,
    CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_STRICT_FLOW_ENABLED:
        true,
    CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_MAX_FUNDING_AGE_SEC:
        Number(30),
    CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_MIN_FUNDING_SOL:
        Number(220),
    CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_MIN_SEED_SOL:
        Number(120),
    CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_MIN_SEED_PCT_OF_LIQ:
        Number(95),
    CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_MAX_COUNTERPARTIES:
        Number(3),
    CREATOR_RISK_MICRO_INBOUND_MAX_SOL: Number(process.env.CREATOR_RISK_MICRO_INBOUND_MAX_SOL ?? 0.001),
    CREATOR_RISK_MICRO_INBOUND_MIN_TRANSFERS: Number(process.env.CREATOR_RISK_MICRO_INBOUND_MIN_TRANSFERS ?? 6),
    CREATOR_RISK_MICRO_INBOUND_MIN_SOURCES: Number(process.env.CREATOR_RISK_MICRO_INBOUND_MIN_SOURCES ?? 2),
    CREATOR_RISK_MICRO_INBOUND_WINDOW_SEC: Number(process.env.CREATOR_RISK_MICRO_INBOUND_WINDOW_SEC ?? 5),
    CREATOR_RISK_DIRECT_AMM_REENTRY_ENABLED: envBool("CREATOR_RISK_DIRECT_AMM_REENTRY_ENABLED", false),
    CREATOR_RISK_DIRECT_AMM_REENTRY_SIG_LIMIT: Number(process.env.CREATOR_RISK_DIRECT_AMM_REENTRY_SIG_LIMIT ?? 8),
    CREATOR_RISK_DIRECT_AMM_REENTRY_WINDOW_SEC: Number(process.env.CREATOR_RISK_DIRECT_AMM_REENTRY_WINDOW_SEC ?? 180),
    CREATOR_RISK_PRECREATE_BURST_BLOCK_ENABLED: envBool("CREATOR_RISK_PRECREATE_BURST_BLOCK_ENABLED", true),
    CREATOR_RISK_PRECREATE_BURST_WINDOW_SEC: Number(process.env.CREATOR_RISK_PRECREATE_BURST_WINDOW_SEC ?? 420),
    CREATOR_RISK_PRECREATE_BURST_SIG_LIMIT: Number(process.env.CREATOR_RISK_PRECREATE_BURST_SIG_LIMIT ?? 180),
    CREATOR_RISK_PRECREATE_BURST_PARSED_TX_LIMIT: Number(process.env.CREATOR_RISK_PRECREATE_BURST_PARSED_TX_LIMIT ?? 120),
    CREATOR_RISK_PRECREATE_BURST_MIN_TRANSFERS: Number(process.env.CREATOR_RISK_PRECREATE_BURST_MIN_TRANSFERS ?? 12),
    CREATOR_RISK_PRECREATE_BURST_MIN_DESTINATIONS: Number(process.env.CREATOR_RISK_PRECREATE_BURST_MIN_DESTINATIONS ?? 12),
    CREATOR_RISK_PRECREATE_BURST_MIN_TRANSFER_SOL: Number(process.env.CREATOR_RISK_PRECREATE_BURST_MIN_TRANSFER_SOL ?? 0.1),
    CREATOR_RISK_PRECREATE_BURST_MIN_TOTAL_SOL: Number(process.env.CREATOR_RISK_PRECREATE_BURST_MIN_TOTAL_SOL ?? 3),
    CREATOR_RISK_PRECREATE_BURST_MIN_MEDIAN_SOL: Number(process.env.CREATOR_RISK_PRECREATE_BURST_MIN_MEDIAN_SOL ?? 0.1),
    CREATOR_RISK_PRECREATE_BURST_MAX_MEDIAN_SOL: Number(process.env.CREATOR_RISK_PRECREATE_BURST_MAX_MEDIAN_SOL ?? 1.3),
    CREATOR_RISK_PRECREATE_BURST_MAX_REL_STDDEV: Number(process.env.CREATOR_RISK_PRECREATE_BURST_MAX_REL_STDDEV ?? 0.18),
    CREATOR_RISK_PRECREATE_BURST_MAX_AMOUNT_RATIO: Number(process.env.CREATOR_RISK_PRECREATE_BURST_MAX_AMOUNT_RATIO ?? 1.6),
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_BLOCK_ENABLED:
        true,
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_MAX_WINDOW_SEC:
        Number(240),
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_MIN_TRANSFERS:
        Number(8),
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_MIN_DESTINATIONS:
        Number(8),
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_MIN_TRANSFER_SOL:
        Number(5),
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_MIN_TOTAL_SOL:
        Number(50),
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_MAX_REL_STDDEV:
        Number(0.12),
    CREATOR_RISK_PRECREATE_LARGE_UNIFORM_MAX_AMOUNT_RATIO:
        Number(1.6),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_BLOCK_ENABLED:
        true,
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MIN_TRANSFERS:
        Number(4),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MIN_DESTINATIONS:
        Number(4),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MIN_TRANSFER_SOL:
        Number(5),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MIN_TOTAL_SOL:
        Number(80),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MIN_MEDIAN_SOL:
        Number(20),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MAX_WINDOW_SEC:
        Number(90),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MIN_SETUP_CREATES:
        Number(20),
    CREATOR_RISK_PRECREATE_DISPERSAL_SETUP_MAX_SETUP_WINDOW_SEC:
        Number(240),
    CREATOR_RISK_CONCENTRATED_INBOUND_BLOCK_ENABLED:
        true,
    CREATOR_RISK_CONCENTRATED_INBOUND_MAX_WINDOW_SEC:
        Number(240),
    CREATOR_RISK_CONCENTRATED_INBOUND_MIN_TRANSFERS:
        Number(12),
    CREATOR_RISK_CONCENTRATED_INBOUND_MAX_SOURCES:
        Number(3),
    CREATOR_RISK_CONCENTRATED_INBOUND_TOP_SOURCE_COUNT:
        Number(2),
    CREATOR_RISK_CONCENTRATED_INBOUND_MIN_TOP_SOURCE_SHARE:
        Number(0.85),
    CREATOR_RISK_CONCENTRATED_INBOUND_MIN_TRANSFER_SOL:
        Number(0.25),
    CREATOR_RISK_CONCENTRATED_INBOUND_MIN_TOTAL_SOL:
        Number(6),
    CREATOR_RISK_CONCENTRATED_INBOUND_MIN_MEDIAN_SOL:
        Number(0.25),
    CREATOR_RISK_CONCENTRATED_INBOUND_MAX_MEDIAN_SOL:
        Number(1.5),
    CREATOR_RISK_CONCENTRATED_INBOUND_MAX_REL_STDDEV:
        Number(0.35),
    CREATOR_RISK_CONCENTRATED_INBOUND_MAX_AMOUNT_RATIO:
        Number(4),
    CREATOR_RISK_CONCENTRATED_INBOUND_MIN_SETUP_CREATES:
        Number(8),
    CREATOR_RISK_CONCENTRATED_INBOUND_MIN_REPEAT_CREATES:
        Number(2),
    CREATOR_RISK_LOOKUP_TABLE_NEAR_CREATE_BLOCK_ENABLED:
        true,
    CREATOR_RISK_LOOKUP_TABLE_NEAR_CREATE_MAX_WINDOW_SEC:
        Number(30),
    CREATOR_RISK_LOOKUP_TABLE_NEAR_CREATE_MIN_LOOKUPS:
        Number(2),
    CREATOR_RISK_LOOKUP_TABLE_NEAR_CREATE_MIN_CREATES:
        Number(20),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_BLOCK_ENABLED: envBool("CREATOR_RISK_REPEAT_CREATE_REMOVE_BLOCK_ENABLED", true),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_WINDOW_SEC: Number(process.env.CREATOR_RISK_REPEAT_CREATE_REMOVE_WINDOW_SEC ?? 600),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_CREATES: Number(process.env.CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_CREATES ?? 2),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_REMOVES: Number(process.env.CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_REMOVES ?? 1),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_CASHOUTS: Number(process.env.CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_CASHOUTS ?? 1),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_CREATE_SOL: Number(process.env.CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_CREATE_SOL ?? 20),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_REMOVE_SOL: Number(process.env.CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_REMOVE_SOL ?? 20),
    CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_CASHOUT_SOL: Number(process.env.CREATOR_RISK_REPEAT_CREATE_REMOVE_MIN_CASHOUT_SOL ?? 2),
    HOLD_CREATOR_RISK_RECHECK_ENABLED: envBool("HOLD_CREATOR_RISK_RECHECK_ENABLED", true),
    HOLD_CREATOR_RISK_RECHECK_INTERVAL_MS: Number(process.env.HOLD_CREATOR_RISK_RECHECK_INTERVAL_MS ?? 1500),
    CREATOR_RISK_FUNDER_REFUND_MIN_SOL: Number(process.env.CREATOR_RISK_FUNDER_REFUND_MIN_SOL ?? 0.05),
    HOLD_CREATOR_CASHOUT_EXIT_ENABLED: envBool("HOLD_CREATOR_CASHOUT_EXIT_ENABLED", true),
    CREATOR_RISK_CASHOUT_ABS_SOL: Number(process.env.CREATOR_RISK_CASHOUT_ABS_SOL ?? 5),
    CREATOR_RISK_CASHOUT_REL_LIQ_PCT: Number(process.env.CREATOR_RISK_CASHOUT_REL_LIQ_PCT ?? 25),
    CREATOR_RISK_CASHOUT_WARN_SCORE: Number(process.env.CREATOR_RISK_CASHOUT_WARN_SCORE ?? 0.5),
    CREATOR_RISK_CASHOUT_EXIT_SCORE: Number(process.env.CREATOR_RISK_CASHOUT_EXIT_SCORE ?? 1),
    SLIPPAGE_PERCENT: Number(process.env.SLIPPAGE_PERCENT ?? 20),
    REQUIRE_RENOUNCED_MINT: envBool("REQUIRE_RENOUNCED_MINT", true),
    REQUIRE_NO_FREEZE: envBool("REQUIRE_NO_FREEZE", true),
    MAX_DEV_HOLDINGS_PCT: Number(process.env.MAX_DEV_HOLDINGS_PCT ?? 20),
    ENFORCE_DEV_HOLDINGS_CHECK: envBool("ENFORCE_DEV_HOLDINGS_CHECK", true),
    DEV_HOLDINGS_MAX_ATTEMPTS: Number(process.env.DEV_HOLDINGS_MAX_ATTEMPTS ?? 3),
    DEV_HOLDINGS_RETRY_DELAY_MS: Number(process.env.DEV_HOLDINGS_RETRY_DELAY_MS ?? 250),
    DEV_HOLDINGS_MAX_DURATION_MS: Number(process.env.DEV_HOLDINGS_MAX_DURATION_MS ?? 2000),
    LOG_STALE_RESUBSCRIBE_MS: Number(process.env.LOG_STALE_RESUBSCRIBE_MS ?? 90000),
    HEALTHCHECK_INTERVAL_MS: Number(process.env.HEALTHCHECK_INTERVAL_MS ?? 15000),
    SIGNATURE_CACHE_TTL_MS: 10 * 60 * 1000,
    SIGNATURE_CACHE_MAX_SIZE: Number(process.env.SIGNATURE_CACHE_MAX_SIZE ?? 5000),
    SOL_PRICE_CACHE_TTL_MS: Number(process.env.SOL_PRICE_CACHE_TTL_MS ?? 30000),
    RUG_HISTORY_CACHE_TTL_MS: Number(process.env.RUG_HISTORY_CACHE_TTL_MS ?? 60 * 1000),
    PAPER_TRADE_ENABLED: envBool("PAPER_TRADE_ENABLED", true),
    PAPER_CREATOR_RISK_PROBATION_ENABLED: envBool("PAPER_CREATOR_RISK_PROBATION_ENABLED", false),
    PAPER_CREATOR_RISK_PROBATION_HOLD_MS: Number(process.env.PAPER_CREATOR_RISK_PROBATION_HOLD_MS ?? 15000),
    PAPER_CREATOR_CASHOUT_PROBATION_HOLD_MS: Number(process.env.PAPER_CREATOR_CASHOUT_PROBATION_HOLD_MS ?? 45000),
    PAPER_CREATOR_RISK_EXTREME_CASHOUT_BLOCK_ENABLED: envBool("PAPER_CREATOR_RISK_EXTREME_CASHOUT_BLOCK_ENABLED", true),
    PAPER_CREATOR_RISK_EXTREME_CASHOUT_MIN_PCT_OF_LIQ: Number(process.env.PAPER_CREATOR_RISK_EXTREME_CASHOUT_MIN_PCT_OF_LIQ ?? 95),
    PAPER_CREATOR_RISK_EXTREME_CASHOUT_MIN_SCORE: Number(process.env.PAPER_CREATOR_RISK_EXTREME_CASHOUT_MIN_SCORE ?? 25),
    PAPER_CREATOR_RISK_EXTREME_PROBATION_CASHOUT_BLOCK_ENABLED:
        true,
    PAPER_CREATOR_RISK_EXTREME_PROBATION_CASHOUT_MIN_SOL:
        Number(15),
    PAPER_CREATOR_RISK_EXTREME_PROBATION_CASHOUT_MIN_PCT_OF_LIQ:
        Number(15),
    PAPER_CREATOR_RISK_EXTREME_PROBATION_CASHOUT_MIN_SCORE:
        Number(4),
    PAPER_CREATOR_RISK_EXTREME_HISTORY_BLOCK_ENABLED:
        true,
    PAPER_CREATOR_RISK_EXTREME_HISTORY_MIN_COUNTERPARTIES:
        Number(100),
    PAPER_CREATOR_RISK_EXTREME_HISTORY_MIN_OUT_TRANSFERS:
        Number(100),
    PAPER_CREATOR_RISK_EXTREME_HISTORY_MAX_IN_TRANSFERS:
        Number(2),
    PAPER_CREATOR_RISK_EXTREME_UNIQUE_COUNTERPARTIES_BLOCK_ENABLED:
        true,
    PAPER_CREATOR_RISK_EXTREME_UNIQUE_COUNTERPARTIES_MIN:
        Number(100),
    PAPER_CREATOR_RISK_EXTREME_UNIQUE_COUNTERPARTIES_MIN_OUT_TRANSFERS:
        Number(100),
    PAPER_CREATOR_RISK_EXTREME_UNIQUE_COUNTERPARTIES_MAX_IN_TRANSFERS:
        Number(25),
    PAPER_CREATOR_RISK_PROBATION_UNIQUE_COUNTERPARTIES_BLOCK_ENABLED:
        true,
    PAPER_CREATOR_RISK_PROBATION_UNIQUE_COUNTERPARTIES_MIN:
        Number(28),
    PAPER_CREATOR_RISK_PROBATION_UNIQUE_COUNTERPARTIES_MIN_OUT_TRANSFERS:
        Number(28),
    PAPER_CREATOR_RISK_PROBATION_UNIQUE_COUNTERPARTIES_MAX_IN_TRANSFERS:
        Number(2),
    PAPER_CREATOR_RISK_PROBATION_LOW_CASHOUT_BLOCK_ENABLED:
        true,
    PAPER_CREATOR_RISK_PROBATION_LOW_CASHOUT_MIN_SOL:
        Number(3),
    PAPER_CREATOR_RISK_PROBATION_LOW_CASHOUT_MIN_PCT_OF_LIQ:
        Number(3),
    PAPER_CREATOR_RISK_PROBATION_LOW_CASHOUT_MIN_SCORE:
        Number(1),
    CREATOR_RESOLUTION_FAIL_OPEN: envBool("CREATOR_RESOLUTION_FAIL_OPEN", false),
    LOW_LIQUIDITY_RECHECK_ENABLED: envBool("LOW_LIQUIDITY_RECHECK_ENABLED", true),
    LOW_LIQUIDITY_RECHECK_WINDOW_MS: Number(process.env.LOW_LIQUIDITY_RECHECK_WINDOW_MS ?? 5000),
    LOW_LIQUIDITY_RECHECK_INTERVAL_MS: Number(process.env.LOW_LIQUIDITY_RECHECK_INTERVAL_MS ?? 300),
    LOW_LIQUIDITY_POOL_COOLDOWN_MS: Number(process.env.LOW_LIQUIDITY_POOL_COOLDOWN_MS ?? 120000),
    MAX_CONCURRENT_OPERATIONS: Number(process.env.MAX_CONCURRENT_OPERATIONS ?? 2),
    // Tetto di getParsedTransaction simultanee per processo worker. Il bot leggeva fino
    // a 40 firme con un Promise.all senza limite, da otto punti diversi e con quattro
    // deep check in parallelo fra loro: il picco non era limitato da niente ed e cosi che
    // il 2026-03-29 e stata bruciata una chiave Helius. Il totale del sistema e questo
    // valore x MAX_CONCURRENT_OPERATIONS.
    RPC_MAX_CONCURRENT_TX_FETCH: Number(process.env.RPC_MAX_CONCURRENT_TX_FETCH || 6),
    // Tetto locale per singola richiesta HTTP: web3.js non ne ha uno. Vedi controls.md 28.
    RPC_REQUEST_TIMEOUT_MS: Number(process.env.RPC_REQUEST_TIMEOUT_MS || 8000),
    // Tetto al RITMO, per processo worker. Diverso da RPC_MAX_CONCURRENT_TX_FETCH, che limita
    // il parallelismo di un solo helper: i deep check creator-risk emettono ~60 richieste in
    // 2,4s con richieste brevi e sequenziali, che nessun tetto di concorrenza rallenta.
    // Il totale verso l'endpoint e questo valore x MAX_CONCURRENT_OPERATIONS. 0 = nessun
    // limite, da usare solo con un endpoint a pagamento. Vedi controls.md 31.
    RPC_MAX_REQUESTS_PER_SEC: Number(process.env.RPC_MAX_REQUESTS_PER_SEC ?? 8),
    QUEUE_MAX_PENDING_SIGNATURES: Number(process.env.QUEUE_MAX_PENDING_SIGNATURES ?? 300),
    // Rete di sicurezza, non una manopola di tuning: un worker che supera questo tempo viene
    // ucciso e il suo slot liberato. Senza, un solo worker appeso su una chiamata RPC che non
    // ritorna mai tiene lo slot per sempre, e con MAX_CONCURRENT_OPERATIONS=2 ne bastano due
    // per fermare l'intero bot (successo il 2026-09-12, vedi controls.md 26). Deve restare
    // sopra AUTO_SELL_DELAY_MS (900s) piu il tempo di valutazione, altrimenti tronca gli hold.
    WORKER_MAX_LIFETIME_MS: Number(process.env.WORKER_MAX_LIFETIME_MS || 1200000),
    // Con 2.856 creazioni/ora contro 360 di capacita la coda e sempre piena: senza TTL
    // il worker riceve pool vecchie di ~50 minuti, gia migrate o gia ruggate. Scartare
    // e corretto, non e una perdita: quella firma non era comunque valutabile in tempo.
    QUEUE_MAX_AGE_MS: Number(process.env.QUEUE_MAX_AGE_MS || 45000),
    // "lifo" prende la firma piu fresca, "fifo" la piu vecchia. Per uno sniper la fresca
    // e l'unica che ha senso; "fifo" resta per riprodurre il comportamento storico.
    QUEUE_ORDER: String(process.env.QUEUE_ORDER || "lifo").toLowerCase(),
    // Nomi di DEX (come in src/services/dex/index.ts) che hanno la precedenza quando hanno
    // lavoro in coda. Serve perche la coda e unica e pump genera ~13 creazioni per ogni
    // pumpswap: a coda satura — e lo e il 99% del tempo — pumpswap viene affamata, e il LIFO
    // peggiora la cosa perche "il piu fresco" coincide quasi sempre con "chi arriva di piu".
    // Vuoto = nessuna precedenza. Vedi controls.md 30.
    QUEUE_PRIORITY_DEX: String(process.env.QUEUE_PRIORITY_DEX ?? "pumpswap"),
    DEFERRED_NO_WSOL_QUEUE_ENABLED: envBool("DEFERRED_NO_WSOL_QUEUE_ENABLED", false),
    DEFERRED_NO_WSOL_QUEUE_MAX_JOBS: Number(process.env.DEFERRED_NO_WSOL_QUEUE_MAX_JOBS ?? 300),
    DEFERRED_NO_WSOL_INITIAL_DELAY_MS: Number(process.env.DEFERRED_NO_WSOL_INITIAL_DELAY_MS ?? 2000),
    DEFERRED_NO_WSOL_MAX_ATTEMPTS: Number(process.env.DEFERRED_NO_WSOL_MAX_ATTEMPTS ?? 14),
    DEFERRED_NO_WSOL_BASE_INTERVAL_MS: Number(process.env.DEFERRED_NO_WSOL_BASE_INTERVAL_MS ?? 3000),
    DEFERRED_NO_WSOL_BACKOFF_MULTIPLIER: Number(process.env.DEFERRED_NO_WSOL_BACKOFF_MULTIPLIER ?? 1.5),
    DEFERRED_NO_WSOL_MAX_INTERVAL_MS: Number(process.env.DEFERRED_NO_WSOL_MAX_INTERVAL_MS ?? 30000),
    DEFERRED_NO_WSOL_MAX_AGE_MS: Number(process.env.DEFERRED_NO_WSOL_MAX_AGE_MS ?? 300000),
    CC_SHADOW_ENABLED: envBool("CC_SHADOW_ENABLED", false),
    CC_SHADOW_QUEUE_MAX_JOBS: Number(process.env.CC_SHADOW_QUEUE_MAX_JOBS ?? 2000),
    CC_SHADOW_FAST_INTERVAL_MS: Number(process.env.CC_SHADOW_FAST_INTERVAL_MS ?? 5000),
    CC_SHADOW_FAST_PHASE_MS: Number(process.env.CC_SHADOW_FAST_PHASE_MS ?? 180000),
    CC_SHADOW_SLOW_INTERVAL_MS: Number(process.env.CC_SHADOW_SLOW_INTERVAL_MS ?? 60000),
    CC_SHADOW_DEX_EVERY_N_SNAPSHOTS: Number(process.env.CC_SHADOW_DEX_EVERY_N_SNAPSHOTS ?? 1),
    CREATOR_RISK_RATE_LIMIT_RETRIES: Number(process.env.CREATOR_RISK_RATE_LIMIT_RETRIES ?? 3),
    CREATOR_RISK_RATE_LIMIT_RETRY_BASE_MS: Number(process.env.CREATOR_RISK_RATE_LIMIT_RETRY_BASE_MS ?? 350),
    CREATOR_RISK_DEEP_CHECK_BUDGET_MS: Number(process.env.CREATOR_RISK_DEEP_CHECK_BUDGET_MS ?? 12000),
    CREATOR_RISK_RECHECK_DEEP_CHECK_BUDGET_MS: Number(process.env.CREATOR_RISK_RECHECK_DEEP_CHECK_BUDGET_MS ?? 2500),
    PAPER_TRADE_MAX_LOSS_PCT: Number(process.env.PAPER_TRADE_MAX_LOSS_PCT ?? 80),
} as const;

export const CONFIG_GROUPS = {
    preBuy: {
        waitMs: CONFIG.PRE_BUY_WAIT_MS,
        signalMinTrades: CONFIG.PRE_BUY_SIGNAL_MIN_TRADES,
        signalMinQuoteImprovementPct: CONFIG.PRE_BUY_SIGNAL_MIN_QUOTE_IMPROVEMENT_PCT,
        strictSignalMinQuoteImprovementPct: CONFIG.PRE_BUY_STRICT_SIGNAL_MIN_QUOTE_IMPROVEMENT_PCT,
        confirmSnapshots: CONFIG.PRE_BUY_CONFIRM_SNAPSHOTS,
        confirmIntervalMs: CONFIG.PRE_BUY_CONFIRM_INTERVAL_MS,
        noWsolRecheckEnabled: CONFIG.PRE_BUY_NO_WSOL_RECHECK_ENABLED,
        noWsolRecheckMaxAttempts: CONFIG.PRE_BUY_NO_WSOL_RECHECK_MAX_ATTEMPTS,
        noWsolRecheckIntervalMs: CONFIG.PRE_BUY_NO_WSOL_RECHECK_INTERVAL_MS,
        noWsolRecheckBackoffMultiplier: CONFIG.PRE_BUY_NO_WSOL_RECHECK_BACKOFF_MULTIPLIER,
        noWsolRecheckMaxIntervalMs: CONFIG.PRE_BUY_NO_WSOL_RECHECK_MAX_INTERVAL_MS,
        forceEntryOnNoWsolSide: CONFIG.FORCE_ENTRY_ON_NO_WSOL_SIDE,
        ultraShortRugGuardEnabled: CONFIG.PRE_BUY_ULTRA_SHORT_RUG_GUARD_ENABLED,
        ultraShortRugGuardWindowMs: CONFIG.PRE_BUY_ULTRA_SHORT_RUG_GUARD_WINDOW_MS,
        ultraShortRugGuardIntervalMs: CONFIG.PRE_BUY_ULTRA_SHORT_RUG_GUARD_INTERVAL_MS,
        ultraShortRugGuardMaxLiqDropPct: CONFIG.PRE_BUY_ULTRA_SHORT_RUG_GUARD_MAX_LIQ_DROP_PCT,
        ultraShortRugGuardMaxQuoteDropPct: CONFIG.PRE_BUY_ULTRA_SHORT_RUG_GUARD_MAX_QUOTE_DROP_PCT,
        revalidationEnabled: CONFIG.PRE_BUY_REVALIDATION_ENABLED,
        finalCreatorRiskRecheckEnabled: CONFIG.PRE_BUY_FINAL_CREATOR_RISK_RECHECK_ENABLED,
        finalRemoveLiqCheckEnabled: CONFIG.PRE_BUY_FINAL_REMOVE_LIQ_CHECK_ENABLED,
        top10CheckEnabled: CONFIG.PRE_BUY_TOP10_CHECK_ENABLED,
        top10MaxPct: CONFIG.PRE_BUY_TOP10_MAX_PCT,
        top10ExcludePool: CONFIG.PRE_BUY_TOP10_EXCLUDE_POOL,
        top1ExternalHolderCheckEnabled: CONFIG.PRE_BUY_TOP1_EXTERNAL_HOLDER_CHECK_ENABLED,
        top1ExternalHolderMaxPct: CONFIG.PRE_BUY_TOP1_EXTERNAL_HOLDER_MAX_PCT,
        top10FailOpen: CONFIG.PRE_BUY_TOP10_FAIL_OPEN,
    },
    hold: {
        autoSellDelayMs: CONFIG.AUTO_SELL_DELAY_MS,
        removeLiqDetectEnabled: CONFIG.HOLD_REMOVE_LIQ_DETECT_ENABLED,
        removeLiqCheckIntervalMs: CONFIG.HOLD_REMOVE_LIQ_CHECK_INTERVAL_MS,
        creatorRiskRecheckEnabled: CONFIG.HOLD_CREATOR_RISK_RECHECK_ENABLED,
        creatorRiskRecheckIntervalMs: CONFIG.HOLD_CREATOR_RISK_RECHECK_INTERVAL_MS,
        creatorCashoutExitEnabled: CONFIG.HOLD_CREATOR_CASHOUT_EXIT_ENABLED,
        suspiciousRelayShortHoldEnabled: CONFIG.HOLD_SUSPICIOUS_RELAY_SHORT_HOLD_ENABLED,
        suspiciousRelayShortHoldMs: CONFIG.HOLD_SUSPICIOUS_RELAY_SHORT_HOLD_MS,
        poolChurnDetectEnabled: CONFIG.HOLD_POOL_CHURN_DETECT_ENABLED,
        sellQuoteCollapseExitEnabled: CONFIG.HOLD_SELL_QUOTE_COLLAPSE_EXIT_ENABLED,
        singleSwapShockExitEnabled: CONFIG.HOLD_SINGLE_SWAP_SHOCK_EXIT_ENABLED,
        hardStopLossExitEnabled: CONFIG.HOLD_HARD_STOP_LOSS_EXIT_ENABLED,
        winnerManagementEnabled: CONFIG.HOLD_WINNER_MANAGEMENT_ENABLED,
    },
    creatorRisk: {
        enabled: CONFIG.CREATOR_RISK_CHECK_ENABLED,
        sigLimit: CONFIG.CREATOR_RISK_SIG_LIMIT,
        parsedTxLimit: CONFIG.CREATOR_RISK_PARSED_TX_LIMIT,
        maxUniqueCounterparties: CONFIG.CREATOR_RISK_MAX_UNIQUE_COUNTERPARTIES,
        relayFundingEnabled: CONFIG.CREATOR_RISK_RELAY_FUNDING_ENABLED,
        setupBurstBlockEnabled: CONFIG.CREATOR_RISK_SETUP_BURST_BLOCK_ENABLED,
        freshFundedHighSeedBlockEnabled: CONFIG.CREATOR_RISK_FRESH_FUNDED_HIGH_SEED_BLOCK_ENABLED,
        directAmmReentryEnabled: CONFIG.CREATOR_RISK_DIRECT_AMM_REENTRY_ENABLED,
    },
    paper: {
        enabled: CONFIG.PAPER_TRADE_ENABLED,
        maxLossPct: CONFIG.PAPER_TRADE_MAX_LOSS_PCT,
        probationEnabled: CONFIG.PAPER_CREATOR_RISK_PROBATION_ENABLED,
        probationHoldMs: CONFIG.PAPER_CREATOR_RISK_PROBATION_HOLD_MS,
    },
    runtime: {
        maxConcurrentOperations: CONFIG.MAX_CONCURRENT_OPERATIONS,
        queueMaxPendingSignatures: CONFIG.QUEUE_MAX_PENDING_SIGNATURES,
        queueMaxAgeMs: CONFIG.QUEUE_MAX_AGE_MS,
        workerMaxLifetimeMs: CONFIG.WORKER_MAX_LIFETIME_MS,
        queueOrder: CONFIG.QUEUE_ORDER,
        queuePriorityDex: CONFIG.QUEUE_PRIORITY_DEX,
        deferredNoWsolQueueEnabled: CONFIG.DEFERRED_NO_WSOL_QUEUE_ENABLED,
        deferredNoWsolQueueMaxJobs: CONFIG.DEFERRED_NO_WSOL_QUEUE_MAX_JOBS,
        deferredNoWsolInitialDelayMs: CONFIG.DEFERRED_NO_WSOL_INITIAL_DELAY_MS,
        deferredNoWsolMaxAttempts: CONFIG.DEFERRED_NO_WSOL_MAX_ATTEMPTS,
        deferredNoWsolBaseIntervalMs: CONFIG.DEFERRED_NO_WSOL_BASE_INTERVAL_MS,
        deferredNoWsolBackoffMultiplier: CONFIG.DEFERRED_NO_WSOL_BACKOFF_MULTIPLIER,
        deferredNoWsolMaxIntervalMs: CONFIG.DEFERRED_NO_WSOL_MAX_INTERVAL_MS,
        deferredNoWsolMaxAgeMs: CONFIG.DEFERRED_NO_WSOL_MAX_AGE_MS,
        ccShadowEnabled: CONFIG.CC_SHADOW_ENABLED,
        ccShadowQueueMaxJobs: CONFIG.CC_SHADOW_QUEUE_MAX_JOBS,
        ccShadowFastIntervalMs: CONFIG.CC_SHADOW_FAST_INTERVAL_MS,
        ccShadowFastPhaseMs: CONFIG.CC_SHADOW_FAST_PHASE_MS,
        ccShadowSlowIntervalMs: CONFIG.CC_SHADOW_SLOW_INTERVAL_MS,
        ccShadowDexEveryNSnapshots: CONFIG.CC_SHADOW_DEX_EVERY_N_SNAPSHOTS,
        lowLiquidityRecheckEnabled: CONFIG.LOW_LIQUIDITY_RECHECK_ENABLED,
        lowLiquidityRecheckWindowMs: CONFIG.LOW_LIQUIDITY_RECHECK_WINDOW_MS,
        lowLiquidityRecheckIntervalMs: CONFIG.LOW_LIQUIDITY_RECHECK_INTERVAL_MS,
    },
} as const;

export const PRE_BUY_CONFIG = CONFIG_GROUPS.preBuy;
export const HOLD_CONFIG = CONFIG_GROUPS.hold;
export const CREATOR_RISK_CONFIG = CONFIG_GROUPS.creatorRisk;
export const PAPER_CONFIG = CONFIG_GROUPS.paper;
export const RUNTIME_CONFIG = CONFIG_GROUPS.runtime;

export const DURING_TRADE_CONFIG = HOLD_CONFIG;

export const PHASE_CONFIG = {
    preBuy: PRE_BUY_CONFIG,
    duringTrade: DURING_TRADE_CONFIG,
    creatorRisk: CREATOR_RISK_CONFIG,
    paper: PAPER_CONFIG,
    runtime: RUNTIME_CONFIG,
} as const;

export const HOLD_WINNER_PROFILE: WinnerManagementProfile = {
    enabled: CONFIG.HOLD_WINNER_MANAGEMENT_ENABLED,
    checkIntervalMs: CONFIG.HOLD_WINNER_CHECK_INTERVAL_MS,
    minHoldMs: CONFIG.HOLD_WINNER_MIN_HOLD_MS,
    armPnlPct: CONFIG.HOLD_WINNER_ARM_PNL_PCT,
    trailingDropPct: CONFIG.HOLD_WINNER_TRAILING_DROP_PCT,
    hardTakeProfitPct: CONFIG.HOLD_WINNER_HARD_TAKE_PROFIT_PCT,
    minPeakSol: CONFIG.HOLD_WINNER_MIN_PEAK_SOL,
    profitFloorPct: CONFIG.HOLD_WINNER_PROFIT_FLOOR_PCT,
};
